### PR TITLE
Fix content styling with ShadyCSS custom CSS properties shim (MSIE 11)

### LINKED ISSUE #88: ShadyDOM: content style scope is not applied when the parent uses `x-scope`
The issue reproduces in `<confirm-dialog>` from Bakery Flow. Symptoms:

- `<confirm-dialog>` contains `<vaadin-dialog>` in the shadow root, but
- `<confirm-dialog>` styles are scoped with `.confirm-dialog-1`
- `<vaadin-dialog-overlay>` applies the `style-scope confirm-dialog` to the content, as expected, but the styles are not applied, because they were scoped to `.confirm-dialog-1` in the first place.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #88

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/89)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-overlay.html, line 107 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/89#-LC3Nnek3YbDFelhoNSs:-LC3Nnek3YbDFelhoNSt:b-c19yvl) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/924b9c62c20d8eaa3579862a7c2a54a3ec484e4d/src/vaadin-overlay.html#L107)):*
> ```HTML
>       styledTemplate.content.appendChild(style);
> 
>       if (window.ShadyCSS) {
> ```

BTW there are multiple checks across this file, and these here do not check for `nativeShadow`, while one below does. Should we make it consistent, and probably only check it once at the top of IIFE  and store in the constant?

---

*[src/vaadin-overlay.html, line 111 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/89#-LC3Myz7EzI_bgpqh1BE:-LC3Myz7EzI_bgpqh1BF:b-ulntnw) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/924b9c62c20d8eaa3579862a7c2a54a3ec484e4d/src/vaadin-overlay.html#L111)):*
> ```HTML
>       }
> 
>       const klass = class OverlayContent extends HTMLElement {
> ```

please annotate as `@private` so it does not show in API docs (at least the "Elements" section)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/89)*

**Comment by platosha** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-overlay.html, line 107 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/89#-LC3Nnek3YbDFelhoNSs:-LCDh7JO6ANbhqOyzlD0:b-717xs1) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/924b9c62c20d8eaa3579862a7c2a54a3ec484e4d/src/vaadin-overlay.html#L107)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW there are multiple checks across this file, and these here do not check for `nativeShadow`, while one below does. Should we make it consistent, and probably only check it once at the top of IIFE  and store in the constant?
</blockquote></details>

This has zero practical effect, since `createOverlayContent` invocation is conditioned to `!nativeShadow`.

I would not want to change the contents of `createOverlayContent`, however, because the component creation mechanics there are matched with what Polymer does, and essentially copy what ShadyCSS README suggests.

Storing another constant in IIFE seems unnecessary, since that would be a duplicate of a present value in ShadyCSS.

---

*[src/vaadin-overlay.html, line 111 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/89#-LC3Myz7EzI_bgpqh1BE:-LCDoTq3CzxByJUGZSlS:bb6zinc) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/924b9c62c20d8eaa3579862a7c2a54a3ec484e4d/src/vaadin-overlay.html#L111)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please annotate as `@private` so it does not show in API docs (at least the "Elements" section)
</blockquote></details>

Done.

Had to wrap in an IIFE to hide it completely.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/89)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/89)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/89#-:-LCYhtpH6Mm0pVYAg6iM:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/vaadin-overlay.html, line 99 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/89#-LCbRfyf2Vl0Ypo9faXP:-LCbRfyf2Vl0Ypo9faXQ:b6io5ku) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/afce4d2642d3759af8b671c6b50a6d72d1a000ca/src/vaadin-overlay.html#L99)):*
> ```HTML
> 
>     const createOverlayContent = (cssText) => {
>       overlayContentCounter++;
> ```

Why not increment the counter in it's usage line, it's a very common pattern, to validate that developer don't forget increasing it. Not a blocker though

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/89)*

**Comment by limonte** [comment]
Overlay's complexity is increasing, more than 500 lines of tricky code to maintain. Lord help us :)

:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/89#-:-LCXcn2D8CcPf_MMLwtH:b-9ykmh3)*

**Pull request merged**
