### PR TITLE
Ignore outside click events and escape when recent overlays opened exist

### LINKED ISSUE #43: Consider a flag to know that the overlay is the last in the stack
When opening nested overlays e.g a vaadin-combo-box inside a vaadin-dialog we might need a way to know if the vaadin-dialog is the last in the stack to prevent closing it on escape or outside clicks.

### PR DESCRIPTION
**Pull request by manolo**
Fixes #43

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/44)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44#-:-Kz_9Y0IKMTyoAhHIXQY:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-overlay.html, line 379 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44#-KzcL1NV5X7JEfhm-98v:-KzcL1NWhXB21YsULbZr:b4u1n8u) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f6bc3d14fbcb85d6237eda82e93ba8ff66a7179b/vaadin-overlay.html#L379)):*
> ```HTML
>        * returns true if this is the last in the opened overlay stack
>        */
>       get last() {
> ```

No need for this to be public `last` -> `_last`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44)*

**Comment by tomivirkki** [comment]
Did you try the approach suggested [here](https://github.com/vaadin/vaadin-overlay/issues/43#issuecomment-346275456) ?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44#-:-KzcPhWEovaybA1mwhfi:b-x3dcmd)*

**Comment by platosha** [comment]
@tomivirkki if the theoretical model in my head is correct, then

- For pressing Esc this approach has no use: only the single focused `<vaadin-overlay>` would get the keyboard press event anyway.

- For the outside click, this kind of an approach would not work: outside click listeners from all the overlays are all on the same `document` node, so simple `stopPropagation` does not skip them. `stopImmediatePropagation` does not skip either: the listeners are added in the same order the overlays are opened, the last overlay cannot stop propagation for the previously added listeners.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44#-:-KzcVMULlpoJi_W9Vc_m:br35lg8)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44#-:-KzcZDvU613Vby5ULLi9:bnfp4nl)*

**Comment by manolo** [comment]
I tried that approach, but means that all elements using the overlay needs to be updated to listen for the custom events fired by the overlay in order to prevent them.  This approach is simpler and fixes the problem at once.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44#-:-KzceQOlJM9BUTLtIFXD:bj1vep4)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-overlay.html, line 379 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44#-KzcL1NV5X7JEfhm-98v:-KzcjPuygfjApc4OJlR1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f6bc3d14fbcb85d6237eda82e93ba8ff66a7179b/vaadin-overlay.html#L379)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

No need for this to be public `last` -> `_last`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/44#-:-Kzcr-G1tRh3pmtgOb1b:bnfp4nl)*

**Pull request merged**
