### PR TITLE
Align renderer API docs with the context-menu [skip ci]

### PR DESCRIPTION
**Pull request by platosha**
Connected to vaadin/components-team-tasks#401
Connected to  vaadin/components-team-tasks#402

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/112)

### CODE REVIEW

**Review by yuriy-fix — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/112)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yuriy-fix — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/112#-:-LJYYNflA5e-NrhN0TVi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @platosha)

___
*[src/vaadin-overlay.html, line 245 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/112#-LJYXl4kCHEAYtvrI8PW:-LJYXl4kCHEAYtvrI8PX:b1wf44a) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/cea259ad09807e8ef89d464e7211cb037f4b9502/src/vaadin-overlay.html#L245)):*
> ```HTML
>            *
>            * **NOTE:** The renderer callback can be called multiple times
>            * with previous content.
> ```

Nit: `previous content` -> `the previous content`

**Review by manolo — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/112#-:-LJZs4jaDPGiu8H7FnZT:b-uwkowd)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @YuriyVaadin)

___
*[src/vaadin-overlay.html, line 245 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/112#-LJYXl4kCHEAYtvrI8PW:-LJZs1_x9SO-N_M6Li2N:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/cea259ad09807e8ef89d464e7211cb037f4b9502/src/vaadin-overlay.html#L245)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Nit: `previous content` -> `the previous content`
</blockquote></details>

Done

**Review by manolo — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/112)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
