### PR TITLE
Fix iron-overlay-canceled listener closure memory leak

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to #134 

The arrow function implies the closure over the class constructor which seems to cause memory leak, as reported by @gatanaso:

screen shot 2018-11-21 at 14 02 12

PR is expected to fix that by eliminating the closure and binding `this` explicitly.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/133)

### CODE REVIEW

**Comment by web-padawan** [comment]
Note: there are 2 more lines related to `vaadin-overlay`, these are dummy click listeners which we needed, and probably still need, as a workaround for iOS Safari.

**Comment by web-padawan** [comment]
Note: looks like in ShadyDOM `removeEventListener` is now called twice, once in `_exitModalState` and the second time in `disconnectedCallback`. I don't anticipate any problems with it, and would prefer not to remove old code in order not to break anything occasionally.

**Comment by web-padawan** [comment]
Looking at the original fix from #14, it seems that this can be simplified. Will probably add some regression test using paper-dialog and then refactor my fix.

**Review by manolo — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/133#-:-LSKkmHLBsN6jcRK7iT5:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by tomivirkki — APPROVED** [review]

**Review by yuriy-fix — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/133#-:-LSPdc0VA2NDjRiL8UGw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
