### PR TITLE
Fire escape-close event

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fire escape-close event before closing on ESC button pressed.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/6)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[test/vaadin-overlay.html, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6#-KqYKJu9D2VmEL_Bi6l9:-KqYKJuAf9Q4xBsp4UDz:b-7g55fc) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5f664a294aa81e2e675c7ca3be5157384868ddb3/test/vaadin-overlay.html#L69)):*
> ```HTML
> 
>       it('should not close on esc if escape-close event was canceled', () => {
>         overlay.addEventListener('escape-close', e => {
> ```

Wrong event name, also the other test event name should be fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6)*

**Comment by yuriy-fix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-overlay.html, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6#-KqYKJu9D2VmEL_Bi6l9:-Kqb6mvmZPeiWLyS-96p:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5f664a294aa81e2e675c7ca3be5157384868ddb3/test/vaadin-overlay.html#L69)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Wrong event name, also the other test event name should be fixed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6)*

**Comment by samiheikki** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-overlay.html, line 168 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6#-Kqb5VHu1icLADH_ddpj:-Kqb5VHu1icLADH_ddpk:bz6lo62) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5f664a294aa81e2e675c7ca3be5157384868ddb3/vaadin-overlay.html#L168)):*
> ```HTML
>       /**
>        * @event vaadin-overlay-escape-press
>        * fired before the `vaadin-overlay` will be closed on ESC button pressed. If canceled the closing of the overlay is canceled as well.
> ```

Can you change `pressed` to `press`.

---

*[vaadin-overlay.html, line 171 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6#-Kqb6PFnyLdsNE7mtMtq:-Kqb6PFnyLdsNE7mtMtr:b-6h5itd) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5f664a294aa81e2e675c7ca3be5157384868ddb3/vaadin-overlay.html#L171)):*
> ```HTML
>        */
>       _escapeListener(event) {
>         var evt = new CustomEvent('vaadin-overlay-escape-press', {bubbles: true, cancelable: true, detail: {sourceEvent: event}});
> ```

As the value of `evt` doesn't change, it should be `const` instead of `var`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6)*

**Comment by yuriy-fix** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-overlay.html, line 168 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6#-Kqb5VHu1icLADH_ddpj:-Kqb7KAU87wQxlKVBF5F:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5f664a294aa81e2e675c7ca3be5157384868ddb3/vaadin-overlay.html#L168)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Can you change `pressed` to `press`.
</blockquote></details>

Done.

---

*[vaadin-overlay.html, line 171 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6#-Kqb6PFnyLdsNE7mtMtq:-Kqb7KjynrX1-bX4iRLa:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5f664a294aa81e2e675c7ca3be5157384868ddb3/vaadin-overlay.html#L171)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

As the value of `evt` doesn't change, it should be `const` instead of `var`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6#-:-KqbA6qD7kplJnav3n2x:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6#-:-KqbAC-YCaoUUJGOSosv:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/6)*

**Pull request merged**
