### PR TITLE
Include the overlay part in the tab focus order

### LINKED ISSUE #68: Overlay should not automatically focus the first focusable element inside it
When I create a `<vaadin-dialog>` with a text field as the first component inside it, I don’t always want that field to get focused automatically when the dialog is opened.

Focusing the text field causes the on-screen keyboard to pop-up at least on Android, which in many cases is unexpected and unwanted by the end user.

Moving the focus to some other element than the overlay itself when it’s opened should be an opt-in decision by the developer, not mandated by the overlay.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #68

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/69)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 374 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/69#-L822uiVStBpVHfcQ-nx:-L822uiVStBpVHfcQ-ny:b-36arn4) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/19240ed3c8a0c08fd6687abc0e77d5e96f253d20/src/vaadin-overlay.html#L374)):*
> ```HTML
>           Polymer.RenderStatus.afterNextRender(this, () => {
>             if (this.focusTrap) {
>               this._cycleTab(0, 0);
> ```

If you add `tabindex="1"` to an element inside the overlay, it still gets focused (instead of the overlay):

```
<vaadin-overlay focus-trap id="overlay2" >
  <template>
    <input tabindex="1"></input>
  </template>
</vaadin-overlay>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/69)*

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-overlay.html, line 374 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/69#-L822uiVStBpVHfcQ-nx:-L82OSZf5O2pcV3nE1rc:b-o6qlcw) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/1b041835b60f50a6c3b574be10993a09a0212b85/src/vaadin-overlay.html#L374)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If you add `tabindex="1"` to an element inside the overlay, it still gets focused (instead of the overlay):

```
<vaadin-overlay focus-trap id="overlay2" >
  <template>
    <input tabindex="1"></input>
  </template>
</vaadin-overlay>
```
</blockquote></details>

This is a feature. A `tabindex="1"` is expected to focus before default `tabindex="0"`.

Consider:

```html
<vaadin-overlay focus-trap id="overlay2" >
  <template>
    <input tabindex="1"></input>
    <button tabindex="0">button</button>
  </template>
</vaadin-overlay>
```

All the elements are in the same DOM scope, hence all `tabindex` values have same level of effect.

After the user opens the overlay, if the overlay is focused instead of input, then the next `tab` will focus the button, because it’s a next element of the same tabindex of `0`. This would be unexpected, because with `tabindex="1"` the input is expected to gain focus before everything else of `tabindex="0"`.

Btw the HTML spec says: “Developers should use caution when using values other than 0 or −1 for their tabindex attributes as this is complicated to do correctly.”

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/69)*

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 374 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/69#-L822uiVStBpVHfcQ-nx:-L82RwBeB5EHNRl6skag:b-6xcf6h) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/1b041835b60f50a6c3b574be10993a09a0212b85/src/vaadin-overlay.html#L374)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This is a feature. A `tabindex="1"` is expected to focus before default `tabindex="0"`.

Consider:

```html
<vaadin-overlay focus-trap id="overlay2" >
  <template>
    <input tabindex="1"></input>
    <button tabindex="0">button</button>
  </template>
</vaadin-overlay>
```

All the elements are in the same DOM scope, hence all `tabindex` values have same level of effect.

After the user opens the overlay, if the overlay is focused instead of input, then the next `tab` will focus the button, because it’s a next element of the same tabindex of `0`. This would be unexpected, because with `tabindex="1"` the input is expected to gain focus before everything else of `tabindex="0"`.

Btw the HTML spec says: “Developers should use caution when using values other than 0 or −1 for their tabindex attributes as this is complicated to do correctly.”
</blockquote></details>

Ok :+1: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/69)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/69#-:-L82Rzpk2KmoALAlWbho:bnfp4nl)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/69#-:-L82S50RkQ81Ni0cPNcU:bnfp4nl)*

**Pull request merged**
