### PR TITLE
chore: move CI builds from travis-ci.org to GitHub actions

### PR DESCRIPTION
**Pull request by vlukashov**
## Description

The CI builds cover the following use cases:
 - run a full set of automated code checks for each PR (see `unit-tests.yml` and `visual-tests.yml` in `.github/workflows/`)
   - when a new PR is open (for any branch having these workflow .yml files)
   - when an open PR gets a new commit (including a force push)
 - do not run automated checks if the commit title includes `skip ci`
   The automated checks are skipped only for that one commit which has `skip ci`. For consequent commits that do not have `skip ci` the checks are executed normally.

The full set of automated tests includes both unit and visual tests:
 - Unit tests are executed with the Polymer 2 source code, and also with the Polymer 3 source code after running the P2-to-P3 conversion script.
   - The unit tests with the Polymer 3 source code are executed in a set of different browsers / platforms (via SauceLabs).
   - The unit tests with the Polymer 2 source code are executed in a few browsers running headlessly in the CI agent.
 - Visual tests are executed with the Polymer 2 source code in Chrome and Firefox (via SauceLabs).

Related to: https://github.com/vaadin/components-team-tasks/issues/586

## Type of change

- [ ] Bugfix
- [ ] Feature
- [x] Internal change

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

**Review by web-padawan — CHANGES_REQUESTED** [review]
The only remaining failing tests are related to the unstable feature:

```
Android GoogleAPI Emulator ✖ test/position-target.html » position target » vertical align top » no overlap » should flip back to default when it fits again

  expected 1152.5 to be close to 1232 +/- 1
    <unknown> at    expectEdgesAligned at position-target.html:88:0
    <unknown> at   Context.<anonymous> at position-target.html:197:0

Android GoogleAPI Emulator ✖ test/position-target.html » position target » vertical align top » no overlap » should flip back to default when it fits again

  expected 1152.5 to be close to 1232 +/- 1
    <unknown> at    expectEdgesAligned at position-target.html:88:0
    <unknown> at   Context.<anonymous> at position-target.html:197:0
```

IMO we can skip these on Android Chrome and add a TODO to investigate later.

**Comment by web-padawan** [comment]
Updated the PR to disable running tests on Android Emulator for now to unlock merging the PR, added a TODO.

**Comment by vlukashov** [comment]
> Updated the PR to disable running tests on Android Emulator for now to unlock merging the PR, added a TODO.

Could you please create a new issue? A TODO will be easily forgotten.

**Comment by web-padawan** [comment]
Created an issue: https://github.com/vaadin/components-team-tasks/issues/591

**Review by web-padawan — APPROVED** [review]

**Pull request merged**
