### PR TITLE
Fix focus trap to account for custom web components with focusable children

### LINKED ISSUE #45: Fix focus trap behavior
The current focus rotating behaviour doesn't take into account focusable elements inside shadow roots of child elements.

Drop the current focus trap implementation, and instead:

- Add a custom <kbd>Tab</kbd> (<kbd>Shift</kbd>+<kbd>Tab</kbd>) keydown listener for the dialog, preventing default action;
- On every keydown, query for all focusable elements from the dialog contents. Use recursive walk to collect elements from inside shadow roots:
  - Add `iron-overlay-behaviour` dependency and use `Polymer.IronFocusablesHelper.getTabbableNodes(node)`, see https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-focusables-helper.html ;
- Find the next (previous in case of <kbd>Shift</kbd>+<kbd>Tab</kbd>) focusable from the query results and do the `focus()` jump in the keydown listener;
- Add a focus trap demo with some fields inside a web component;
- Add tests.

This should result in the focus rotating natively inside a "focus trapping" overlay

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #45
Closes #46
Closes #54

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/58)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/index.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25bLEabaMZ_XBJSij8:-L25bLEb--7myDlIAy1d:bc5d1tw) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/demo/index.html#L67)):*
> ```HTML
> 
>             <hr size="1" />
>             <h3>Custom components also participate in focus trap</h3>
> ```

This demo works fine even with the previous version. Custom components per se weren't the issue with focus trap but focusable elements inside a shadow root.

---

*[src/vaadin-overlay.html, line 354 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25hNnnBk3duvFcvNJK:-L25hNnnBk3duvFcvNJL:bavmpj6) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/src/vaadin-overlay.html#L354)):*
> ```HTML
>           // Cycle to the next button
>           if (!event.shiftKey) {
>             this._setFocus(focusedElementIndex, 1, focusableElements);
> ```

Instead of increasing the number of parameters for this function, could we decrease them to `increment` only? The `focusableElements` and `focusedElementIndex` variables aren't needed in this scope so it's kind of weird to define them here. They can be initiated inside `_setFocus` (consider renaming).

---

*[src/vaadin-overlay.html, line 503 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25fzT6xYm-9rrxhtpJ:-L25fzT6xYm-9rrxhtpK:b-o0e5y4) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/src/vaadin-overlay.html#L503)):*
> ```HTML
> 
>       // borrowed from jqeury $(elem).is(':visible') implementation
>       _isVisible(elem) {
> ```

This can be removed now. `getTabbableNodes` already excludes hidden elements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[src/vaadin-overlay.html, line 503 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25fzT6xYm-9rrxhtpJ:-L25k8OlyEG0kDynnKUZ:bn1wz0t) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/src/vaadin-overlay.html#L503)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This can be removed now. `getTabbableNodes` already excludes hidden elements.
</blockquote></details>

:thumbsup:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[demo/index.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25bLEabaMZ_XBJSij8:-L25kK262FIPFtyQRaRz:b6bqben) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/demo/index.html#L67)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This demo works fine even with the previous version. Custom components per se weren't the issue with focus trap but focusable elements inside a shadow root.
</blockquote></details>

Pushed these changes so you guys can take a look before I complete the test implementation. Tests coming up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[src/vaadin-overlay.html, line 354 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25hNnnBk3duvFcvNJK:-L25kffnqTSD32C9WtYn:b860ty4) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/src/vaadin-overlay.html#L354)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Instead of increasing the number of parameters for this function, could we decrease them to `increment` only? The `focusableElements` and `focusedElementIndex` variables aren't needed in this scope so it's kind of weird to define them here. They can be initiated inside `_setFocus` (consider renaming).
</blockquote></details>

Will take a look at the functions as soon as I'm done with the test, so I can properly understand your comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[src/vaadin-overlay.html, line 354 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25hNnnBk3duvFcvNJK:-L2LFRtZhXI5DvyahhMD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/src/vaadin-overlay.html#L354)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Will take a look at the functions as soon as I'm done with the test, so I can properly understand your comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[src/vaadin-overlay.html, line 503 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25fzT6xYm-9rrxhtpJ:-L2LFUkRkE4su0yQRfad:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/src/vaadin-overlay.html#L503)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

:thumbsup:
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[demo/index.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25bLEabaMZ_XBJSij8:-L2LFmwEOkRmOe6aw3yR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/demo/index.html#L67)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Pushed these changes so you guys can take a look before I complete the test implementation. Tests coming up.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by tomivirkki** [comment]
*[demo/index.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25bLEabaMZ_XBJSij8:-L2OjiuO7wnntKrOjLKQ:b-ah9klc) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/demo/index.html#L67)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Let's drop this addition to the demo. Doesn't really bring extra value and bloats the demo overlay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[demo/index.html, line 67 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L25bLEabaMZ_XBJSij8:-L2OmkELg1rIYzrVYeQO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5c41b73053bdbcad8014eeb1e417e3da5f9734a5/demo/index.html#L67)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Let's drop this addition to the demo. Doesn't really bring extra value and bloats the demo overlay.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by tomivirkki** [comment]
*[demo/index.html, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2On9uraidxDghjQ53Q:-L2On9uraidxDghjQ53R:b-hwnnjc) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/44b0f52a8085a11f126bba00f25cdfe07ee40f64/demo/index.html#L12)):*
> ```HTML
>   <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
>   <link rel="import" href="../../vaadin-button/vaadin-button.html">
>   <link rel="import" href="../../vaadin-date-picker/vaadin-date-picker.html">
> ```

Remove these changes also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[demo/index.html, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2On9uraidxDghjQ53Q:-L2Oni3lCv9iGIxfYt_2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/44b0f52a8085a11f126bba00f25cdfe07ee40f64/demo/index.html#L12)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Remove these changes also
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-:-L2OoOAaV-ni5Dsbp2Tp:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[test/vaadin-overlay.html, line 66 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2Oou7v3VA2-p9LzxX0:-L2Oou7v3VA2-p9LzxX1:b-c7sydv) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9256e671bb154a6a6c7d79527a651ed0cf1c6a80/test/vaadin-overlay.html#L66)):*
> ```HTML
>   <test-fixture id="focus-trap">
>     <template>
>       <div id="focusTrap">
> ```

nit: Unnecessary wrapper. Not a blocker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[test/vaadin-overlay.html, line 66 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2Oou7v3VA2-p9LzxX0:-L2OsDANkWpl3rAJB9Hd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9256e671bb154a6a6c7d79527a651ed0cf1c6a80/test/vaadin-overlay.html#L66)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

nit: Unnecessary wrapper. Not a blocker
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[bower.json, line 48 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PHc6lWA78mKggwKKL:-L2PHc6lWA78mKggwKKM:btq04rh) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/bower.json#L48)):*
> ```JSON
>     "vaadin-list-box": "master",
>     "web-component-tester": "^6.0.0",
>     "vaadin-ordered-layout": "master"
> ```

why was this line added?

---

*[src/vaadin-overlay.html, line 492 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PI40IR2oKh0vQta3Y:-L2PI40IR2oKh0vQta3Z:b-cysqze) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/src/vaadin-overlay.html#L492)):*
> ```HTML
>       }
> 
>       _getFocusableElements(container) {
> ```

where is this method called with the `container` argument passed? I can not see any usage of it.

---

*[test/vaadin-overlay.html, line 11 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PIa8ZpP8YvNc4CrO0:-L2PIa8ZpP8YvNc4CrO1:b-abeasr) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/test/vaadin-overlay.html#L11)):*
> ```HTML
>   <link rel="import" href="../../vaadin-text-field/vaadin-text-field.html">
>   <link rel="import" href="../vaadin-overlay.html">
>   <link rel="import" href="../../polymer/polymer.html">
> ```

no need for separate polymer.html import here, elements already import it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by tomivirkki** [comment]
*[test/vaadin-overlay.html, line 11 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PIa8ZpP8YvNc4CrO0:-L2PK5joARvyafMvxK8l:bj5ss54) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/test/vaadin-overlay.html#L11)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

no need for separate polymer.html import here, elements already import it
</blockquote></details>

Need an import for `Polymer.Element` however since it's used for `container-with-shadow` element

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[src/vaadin-overlay.html, line 492 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PI40IR2oKh0vQta3Y:-L2PKT66JTvQCQciukUP:b-d4ozz7) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/src/vaadin-overlay.html#L492)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

where is this method called with the `container` argument passed? I can not see any usage of it.
</blockquote></details>

Seems I had eventually removed code that required that parameter be there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[bower.json, line 48 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PHc6lWA78mKggwKKL:-L2PLV78aiud9FOiZur6:b-fe292n) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/bower.json#L48)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

why was this line added?
</blockquote></details>

A dependency I forgot to remove after I removed code that previously required it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[src/vaadin-overlay.html, line 492 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PI40IR2oKh0vQta3Y:-L2PMAODC-2eyf-QqDuE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/src/vaadin-overlay.html#L492)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

Seems I had eventually removed code that required that parameter be there.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[bower.json, line 48 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PHc6lWA78mKggwKKL:-L2PMHEGjxTdGEPXS7B8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/bower.json#L48)):*
<details><summary><i>Previously, vicsstar (Victor Igbokwe) wrote…</i></summary><blockquote>

A dependency I forgot to remove after I removed code that previously required it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by vicsstar** [comment]
*[test/vaadin-overlay.html, line 11 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-L2PIa8ZpP8YvNc4CrO0:-L2Pkf1Y8OCz6avSuHiW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/354303e615118aa2d76b6ab4bf4d8f94eadc43b6/test/vaadin-overlay.html#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Need an import for `Polymer.Element` however since it's used for `container-with-shadow` element
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/58#-:-L2VEg4fCZ0tqnOQ6SYf:bnfp4nl)*

**Pull request merged**
