### PR TITLE
Prevent late detaching when `opened` is true

### LINKED ISSUE #80: Overlay is throwing exception when toggling it quickly
```
Uncaught TypeError: Cannot read property 'insertBefore' of null
    at HTMLElement._detachOverlay (vaadin-overlay.html:430)
    at HTMLElement.listener (vaadin-overlay.html:417)
_detachOverlay @ vaadin-overlay.html:430
listener @ vaadin-overlay.html:417
```

Live demo: https://cdn.vaadin.com/vaadin-dropdown-menu/1.0.0-beta3/demo/#dropdown-menu-basic-demos

peek 2018-04-18 10-19

Steps to reproduce:

- focus any dropdown-menu
- quickly press <kbd>Space</kbd> several times

### PR DESCRIPTION
**Pull request by limonte**
Fixes #80 

The test suite is in https://github.com/vaadin/vaadin-dropdown-menu/pull/116

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/84)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LATQh_4183SBtoKNkNZ:-LATQh_4183SBtoKNkN_:b-c8805o) (no related file):*
No tests? :-/

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LATQh_4183SBtoKNkNZ:-LATUxe76OtoE2ULs8bH:b-ibgwnp) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

No tests? :-/
</blockquote></details>

As mentioned in the PR description, the test is here https://github.com/vaadin/vaadin-dropdown-menu/pull/116

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LATQh_4183SBtoKNkNZ:-LAXfQtu798shYT2Bmjv:bxfvxfs) (no related file):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

As mentioned in the PR description, the test is here https://github.com/vaadin/vaadin-dropdown-menu/pull/116
</blockquote></details>

I'm not able to write a test case for `vaadin-overlay`, but since tests of `vaadin-dropdown-menu` are included https://github.com/vaadin/vaadin-overlay/blob/master/test/index.html#L30 I guess, that's good enough.

Tests in https://github.com/vaadin/vaadin-dropdown-menu/pull/116 are failing and therefore proving this issue, once this PR is merged and the new patch version of `vaadin-overlay` is released, I will re-run CI builds for vaadin-dropdown-menu

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LATQh_4183SBtoKNkNZ:-LAYHgAtCEkjYSum38hP:b-6zze48) (no related file):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I'm not able to write a test case for `vaadin-overlay`, but since tests of `vaadin-dropdown-menu` are included https://github.com/vaadin/vaadin-overlay/blob/master/test/index.html#L30 I guess, that's good enough.

Tests in https://github.com/vaadin/vaadin-dropdown-menu/pull/116 are failing and therefore proving this issue, once this PR is merged and the new patch version of `vaadin-overlay` is released, I will re-run CI builds for vaadin-dropdown-menu
</blockquote></details>

OK *sigh*

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-:-LAYKfBUCXr5NSDHxRJ7:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 480 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LAlaEtz4bpxpe7j25cQ:-LAlaEtz4bpxpe7j25cR:bdclrgf) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/3730fca807fa98f674e0d80c7aa45f0ed60d28f7/src/vaadin-overlay.html#L480)):*
> ```HTML
> 
>       _detachOverlay() {
>         if (this.opened || !this._placeholder.parentNode) {
> ```

Why is this.opened checked? All the new tests pass fine without it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-overlay.html, line 480 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LAlaEtz4bpxpe7j25cQ:-LAmM6Jq5fK-gcEPOYhV:bn9yykj) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/3730fca807fa98f674e0d80c7aa45f0ed60d28f7/src/vaadin-overlay.html#L480)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this.opened checked? All the new tests pass fine without it.
</blockquote></details>

Added the comment to the code.

As mentioned in the PR description, test case for this functionality in in https://github.com/vaadin/vaadin-dropdown-menu/pull/116

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84)*

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 480 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LAlaEtz4bpxpe7j25cQ:-LAmOuFsBwZ33ZpCdV12:b-v793i6) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/3730fca807fa98f674e0d80c7aa45f0ed60d28f7/src/vaadin-overlay.html#L480)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Added the comment to the code.

As mentioned in the PR description, test case for this functionality in in https://github.com/vaadin/vaadin-dropdown-menu/pull/116
</blockquote></details>

I meant that the test cases in vaadin/vaadin-dropdown-menu#116 pass even without it. There shouldn't be need for a comment like this, it should be covered in the test cases.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/vaadin-overlay.html, line 480 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LAlaEtz4bpxpe7j25cQ:-LAmSzxV5APA7Vu4qRaO:b-1p7mtr) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/3730fca807fa98f674e0d80c7aa45f0ed60d28f7/src/vaadin-overlay.html#L480)):*
> I meant that the test cases in vaadin/vaadin-dropdown-menu#116 pass even without it. 

Nope.



https://travis-ci.org/vaadin/vaadin-dropdown-menu/builds/369147476

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84)*

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 480 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84#-LAlaEtz4bpxpe7j25cQ:-LAmkSQN8reXTCaayzrQ:b-tud7nu) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/3730fca807fa98f674e0d80c7aa45f0ed60d28f7/src/vaadin-overlay.html#L480)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> I meant that the test cases in vaadin/vaadin-dropdown-menu#116 pass even without it. 

Nope.



https://travis-ci.org/vaadin/vaadin-dropdown-menu/builds/369147476
</blockquote></details>

Without the this.opened check? At least passed locally

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/84)*

**Comment by limonte** [comment]
Closed in favor of https://github.com/vaadin/vaadin-overlay/pull/85

**Pull request merged**
