### PR TITLE
Fix tabbable nodes collection to be not Polymer specific

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes vaadin/vaadin-dialog#112

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/126)

### CODE REVIEW

**Comment by tomivirkki** [comment]
___
*[src/vaadin-overlay.html, line 139 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/126#-LN9R4kx701h9TaD1MPh:-LN9R4kx701h9TaD1MPi:b-46wq3g) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e2d910c108b9061383931f866f015597dd871d76/src/vaadin-overlay.html#L139)):*
> ```HTML
>     };
> 
>     Polymer.IronFocusablesHelper._collectTabbableNodes = function(node, result) {
> ```

Monkey patching a function from another library can be dangerous, especially a private one with references to another private function. Is there any other way to fix this?

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/126)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @web-padawan)

___
*[src/vaadin-overlay.html, line 139 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/126#-LN9R4kx701h9TaD1MPh:-LN9YkZwBGCa_VOtcuib:buw2xkf) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e2d910c108b9061383931f866f015597dd871d76/src/vaadin-overlay.html#L139)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Monkey patching a function from another library can be dangerous, especially a private one with references to another private function. Is there any other way to fix this?
</blockquote></details>

I was considering the following options:
1. re-writing the whole helper under Vaadin namespace
2. extending the helper (using it as a prototype)
3. monkey-patching the helper
4. applying fix for helper and asking Polymer team for releases, both P2 and P3

The last option would be the best but it could take weeks to get those releases from the Polymer team. And rewriting all the code for just 1 line with `root` seemed an overkill.

Should we go ahead and have our own helper here now?

**Comment by tomivirkki** [comment]
___
*[src/vaadin-overlay.html, line 139 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/126#-LN9R4kx701h9TaD1MPh:-LN9tbai-OUuJsOq14hQ:b-j9n0vl) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e2d910c108b9061383931f866f015597dd871d76/src/vaadin-overlay.html#L139)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

I was considering the following options:
1. re-writing the whole helper under Vaadin namespace
2. extending the helper (using it as a prototype)
3. monkey-patching the helper
4. applying fix for helper and asking Polymer team for releases, both P2 and P3

The last option would be the best but it could take weeks to get those releases from the Polymer team. And rewriting all the code for just 1 line with `root` seemed an overkill.

Should we go ahead and have our own helper here now?
</blockquote></details>

Yeah, having our own copy without the legacy imports (if possible) is probably the best choice for now

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/126)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @tomivirkki)

___
*[src/vaadin-overlay.html, line 139 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/126#-LN9R4kx701h9TaD1MPh:-LNA4ofABxev4m1faorR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e2d910c108b9061383931f866f015597dd871d76/src/vaadin-overlay.html#L139)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Yeah, having our own copy without the legacy imports (if possible) is probably the best choice for now
</blockquote></details>

Done.

**Review by tomivirkki — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/126#-:-LNA_l-e0BI3a4aWgUyG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
