### PR TITLE
Fix/demo es6

### LINKED ISSUE #100: Renderer function demo is not working in IE11
Renderer demo is not working in IE11

### PR DESCRIPTION
**Pull request by sohrabtaee**
Fixes #100

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/101)

### CODE REVIEW

**Review by manolo — CHANGES_REQUESTED** [review]
You need to target this PR to `renderer-preview` branch

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/101#-:-LHg3FIUAjY-hoGU5GTE:b-es3wxn)* status: all files reviewed, 1 unresolved discussion (waiting on @sohrabtaee, @tomivirkki, @platosha, and @YuriyVaadin)

___
*[demo/index.html, line 180 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/101#-LHg2wzYElNP-ob9VQMQ:-LHg2wzZ33g1WUbzpYCz:bynie96) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/37398c713e5acf60514c71414268e2f225f3208d/demo/index.html#L180)):*
> ```HTML
>         <script>
>           document.getElementById('button-overlay-pointer').addEventListener('click', function(event) {
>             var overlay = event.target.previousElementSibling;
> ```

not need to change `const` it works in IE11

**Review by sohrabtaee — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/101)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @manolo, @tomivirkki, @platosha, and @YuriyVaadin)

___
*[demo/index.html, line 180 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/101#-LHg2wzYElNP-ob9VQMQ:-LHgLhUTDNvJ5EhdxJio:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/37398c713e5acf60514c71414268e2f225f3208d/demo/index.html#L180)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

not need to change `const` it works in IE11
</blockquote></details>

Done.

**Review by yuriy-fix — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/101)* status: all files reviewed, 1 unresolved discussion (waiting on @manolo, @tomivirkki, and @platosha)

**Comment by tomivirkki** [comment]
The builds are failing, fix

**Comment by tomivirkki** [comment]
___
*[demo/index.html, line 200 at r4](https://reviewable.io/reviews/vaadin/vaadin-overlay/101#-LHhfwLUAZSNmm8e_vTF:-LHhfwLVELfdypViYdHG:bv4oqni) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/1bf892cb8c2075f849ccf52b5e927df553fc2d95/demo/index.html#L200)):*
> ```HTML
>               'top: ' + rect.bottom + 'px;' +
>               'left: ' + rect.left + 'px;' +
>               'right: ' + document.documentElement.clientWidth - rect.right + 'px;' +
> ```

I think it's this line that breaks the demo

**Review by sohrabtaee — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/101)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin, @tomivirkki, and @platosha)

___
*[demo/index.html, line 200 at r4](https://reviewable.io/reviews/vaadin/vaadin-overlay/101#-LHhfwLUAZSNmm8e_vTF:-LHhjNVGDOyhUa10XGHC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/1bf892cb8c2075f849ccf52b5e927df553fc2d95/demo/index.html#L200)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I think it's this line that breaks the demo
</blockquote></details>

Done.

**Review by tomivirkki — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/101#-:-LHhkNrH9zHDNTqAAKIZ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @platosha)

**Pull request merged**
