### PR TITLE
Fix scoping on ShadyCSS to survive flush

### PR DESCRIPTION
**Pull request by platosha**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/79)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-overlay.html, line 462 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/79#-LAIdKIZDqkXWi6q6qxb:-LAIdKI_-dweCLQ0R435:b-ty03le) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/2feb1a5f1d448f99cd67a83966dc2186a1d1d031/src/vaadin-overlay.html#L462)):*
> ```HTML
>         document.body.appendChild(this);
>         if (this._shadyStyleScope) {
>           this.$.content.setAttribute('is', this._shadyStyleScope);
> ```

this line isn't self-explanatory, please add a comment with the explanation why it's here

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/79)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/79#-:-LAIdm7N0KLop9YtpbCc:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/79#-:-LAIiDVx-My7My0AST9z:bnfp4nl)*

**Comment by platosha** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-overlay.html, line 462 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/79#-LAIdKIZDqkXWi6q6qxb:-LAItcba8u3qCxOTQQhu:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/2feb1a5f1d448f99cd67a83966dc2186a1d1d031/src/vaadin-overlay.html#L462)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

this line isn't self-explanatory, please add a comment with the explanation why it's here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/79)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/79#-:-LAJ-Zv01R2ipqqdiwY0:bnfp4nl)*

**Pull request merged**
