### PR TITLE
Fire outside-click event. Set default withBackdrop to false.

### PR DESCRIPTION
**Pull request by yuriy-fix**
Adding an event for tracking closing on outside click. Setting the default displaying of the backdrop to false

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/5)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Needs tests

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-overlay.html, line 145 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqSDlek3B__5xE2juPT:-KqSDlek3B__5xE2juPU:beubipe) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/b07b421e000e8faefb194ed12155557c9632e147/vaadin-overlay.html#L145)):*
> ```HTML
>        */
>       /**
>       * Fired after the `vaadin-dropdown` closes. If prevented the closing of the overlay is prevented as well.
> ```

The description isn't correct.
Indentation also needs to be aligned.
Maybe preferably "If canceled, the closing.."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-:-KqSEDKTbk0vRN2s1mU6:b-we5z6v)*

**Comment by yuriy-fix** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-overlay.html, line 145 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqSDlek3B__5xE2juPT:-KqSdbMFPYhI6Id_6zGI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/b07b421e000e8faefb194ed12155557c9632e147/vaadin-overlay.html#L145)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The description isn't correct.
Indentation also needs to be aligned.
Maybe preferably "If canceled, the closing.."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5)*

**Comment by tomivirkki** [comment]
*[test/vaadin-overlay.html, line 65 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqT80o3dcFAKtfBIP55:-KqT80o3dcFAKtfBIP56:b-kcqxk0) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/a198a69f81cfe4b4d6915545a46a6d50c4a892cf/test/vaadin-overlay.html#L65)):*
> ```HTML
>       });
> 
>       it('should not close if outside-click event was canceled', () => {
> ```

The test should fail if the related change is missing. This test passes even if you run it on master so it doesn't test the correct thing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5)*

**Comment by yuriy-fix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-overlay.html, line 65 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqT80o3dcFAKtfBIP55:-KqWgDq2bZSZT8k8GFYb:bt2vr1b) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/a198a69f81cfe4b4d6915545a46a6d50c4a892cf/test/vaadin-overlay.html#L65)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The test should fail if the related change is missing. This test passes even if you run it on master so it doesn't test the correct thing.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5)*

**Comment by tomivirkki** [comment]
*[analysis.json, line 487 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqWmEaPLzYu-kGuY_tr:-KqWmEaPLzYu-kGuY_ts:b-yxjp1k) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5147e20f2e07e2d60a3387822eb545f25ee59f63/analysis.json#L487)):*
> ```JSON
>             {
>               "type": "CustomEvent",
>               "name": "outside-close",
> ```

The documentation says "outside-close" while the event is actually "outside-click"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5)*

**Comment by yuriy-fix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[analysis.json, line 487 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqWmEaPLzYu-kGuY_tr:-KqWmm1rC_qka4PdnNwZ:bt2vr1b) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5147e20f2e07e2d60a3387822eb545f25ee59f63/analysis.json#L487)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The documentation says "outside-close" while the event is actually "outside-click"?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5)*

**Comment by limonte** [comment]
will this solution work for both cases: with and without backdrop?

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-overlay.html, line 105 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqWlVEEX1JuiqhsfRFR:-KqWlVEEX1JuiqhsfRFS:b-rkzl6n) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5147e20f2e07e2d60a3387822eb545f25ee59f63/vaadin-overlay.html#L105)):*
> ```HTML
>           withBackdrop: {
>             type: Boolean,
>             value: false,
> ```

This is a radical change. Separate it in other PR with tests and the demo example of using `vaadin-overlay` with backdrop.

It's a good practice not to combine multiple features/changes in one PR.

---

*[vaadin-overlay.html, line 135 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqWlfYStYdXCH0RN8ic:-KqWlfYStYdXCH0RN8id:bbicxdo) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5147e20f2e07e2d60a3387822eb545f25ee59f63/vaadin-overlay.html#L135)):*
> ```HTML
>       _setTemplateFromNodes(nodes) {
>         this.template = nodes.filter(node => node.localName && node.localName === 'template')[
>           0] || this.template;
> ```

No need in line break here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-:-KqWma9VHM7ZiZoESaLZ:bg1h7hs)*

**Comment by yuriy-fix** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-overlay.html, line 105 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqWlVEEX1JuiqhsfRFR:-KqWneanGhT65AsXVuD0:b-a2ujfl) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5147e20f2e07e2d60a3387822eb545f25ee59f63/vaadin-overlay.html#L105)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This is a radical change. Separate it in other PR with tests and the demo example of using `vaadin-overlay` with backdrop.

It's a good practice not to combine multiple features/changes in one PR.
</blockquote></details>

Changed.

---

*[vaadin-overlay.html, line 135 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-KqWlfYStYdXCH0RN8ic:-KqWndgCtrQz4HDWPYoE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/5147e20f2e07e2d60a3387822eb545f25ee59f63/vaadin-overlay.html#L135)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

No need in line break here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/5#-:-KqWwYDvwv8INVz6HDcj:bnfp4nl)*

**Pull request merged**
