### PR TITLE
Change outside listener: click -> mousedown/mouseup

### PR DESCRIPTION
**Pull request by limonte**
Fixes https://github.com/vaadin/vaadin-dialog/issues/5

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/20)

### CODE REVIEW

**Comment by limonte** [comment]
Pro-tip for reviewers: add `?w=1` to the URL before doing CR.

**Comment by tomivirkki** [comment]
This solution is quite complex, and depending on simulated click (mousedown+mouseup) seems dangerous. All you really need is to move the click's composedpath check to mousedown phase. Here's an example: https://github.com/vaadin/vaadin-overlay/commit/7ec3923414bb70e4d195dd68b06679539bbd2f0f

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20#-:-KsmWTvp-V5FG3OL6fjF:b-x3i34p)*

**Comment by limonte** [comment]
> All you really need is to move the click's composedpath check to mousedown phase. Here's an example: 7ec3923

That's the solution which will indeed fix the reported issue (mousedown on content, mouseup on backdrop). But the opposite issue (mousedown on backdrop, mouseup on content) will still remain. My solution covers both cases.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20#-:-KsmzLCySEDbRwcGi2lg:bmfejo0)*

**Comment by tomivirkki** [comment]
Here https://github.com/vaadin/vaadin-overlay/commit/e0edd28051f28c6f839058b84510b228186d0eb5 Now it covers both cases. Added 1 more line.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20#-:-KsmzxKI-qVinj7rKel6:bvkuejk)*

**Comment by limonte** [comment]
> Here e0edd28 Now it covers both cases. Added 1 more line.

Done, thanks!

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20#-:-Ksr4GebPteSP1BFrs0l:b-52bm0k)*

**Comment by tomivirkki** [comment]
*[test/vaadin-overlay.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20#-Ksr926QUpfO7ySsc5gH:-Ksr926QUpfO7ySsc5gI:baa97ms) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/2bae472cf8fc7b4122dfd100000adece7ab3d59b/test/vaadin-overlay.html#L36)):*
> ```HTML
>     const click = (el) => {
>       el.dispatchEvent(new CustomEvent('mousedown', {bubbles: true, composed: true}));
>       el.dispatchEvent(new CustomEvent('click', {bubbles: true, composed: true}));
> ```

The order of how these events occur is mousedown -> mouseup -> click

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-overlay.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20#-Ksr926QUpfO7ySsc5gH:-KsrEZzfRHjNuVELs9Mg:by11lav) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/2bae472cf8fc7b4122dfd100000adece7ab3d59b/test/vaadin-overlay.html#L36)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The order of how these events occur is mousedown -> mouseup -> click
</blockquote></details>

Oops, changed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20)*

**Comment by tomivirkki** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/20#-:-KsrHyGMHL6OW2XY9FtX:bg7igkv)*

**Pull request merged**
