### PR TITLE
Adding renderer

### LINKED ISSUE #95: Content renderer
Child of vaadin/components-team-tasks#365

See the spec: https://github.com/vaadin/components-team-tasks/issues/365#issuecomment-404149148

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fixes #95

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)

### CODE REVIEW

**Review by platosha — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: all files reviewed, 5 unresolved discussions (waiting on @YuriyVaadin)

___
*[demo/index.html, line 105 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHE7Kl6CDDvneWHcg7Y:-LHE7Kl753gsoMwfWZ5T:b-d9pvrh) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/07dbabf337f9e23b5880f4edb57db85a32dd1ea8/demo/index.html#L105)):*
> ```HTML
>     <h3>Using renderer</h3>
>     <p>
>       By default the overlay is using Polymer's Templatizer and stamp/update the instances.
> ```

BTW nitpicking, but the wording could be simpler a bit.

By default, the overlay uses the content from its template using `Polymer.Templatize`.

Alternatively, the content can be provided using the `renderer` callback function. 

NOTE: When the `renderer` property is defined, the `<template>` content is not used.
___
*[demo/index.html, line 112 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHE70qYAO-1QZW9SBGn:-LHE70qYAO-1QZW9SBGo:b-40nrem) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/07dbabf337f9e23b5880f4edb57db85a32dd1ea8/demo/index.html#L112)):*
> ```HTML
>       <template>
>         <vaadin-overlay id="overlay-renderer">
>           <template>
> ```

Using both `<template>` and `.renderer` is not a typical use case. These are alternative ways of using the overlay, so let us not put them both in the same demo.
___
*[demo/index.html, line 118 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHE9UVIANW6gLkvKpwA:-LHE9UVIANW6gLkvKpwB:b-8p2ml4) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/07dbabf337f9e23b5880f4edb57db85a32dd1ea8/demo/index.html#L118)):*
> ```HTML
> 
>         <vaadin-button onclick="document.getElementById('overlay-renderer').opened = true">
>           Show overlay
> ```

`Show *the* overlay`, it’s the particular overlay.
___
*[demo/index.html, line 124 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHEARZC1hZ1cyt0vKRN:-LHEARZDCln8gmS9_ub-:b77bi7h) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/07dbabf337f9e23b5880f4edb57db85a32dd1ea8/demo/index.html#L124)):*
> ```HTML
>           const overlay = document.querySelector('#overlay-renderer');
>           overlay.renderer = root => {
>             if (root.firstChild) {
> ```

We should definitely mention why we check the `firstChild` like this. Maybe describe that the renderer callback can be called multiple times with the same in the description, and make a small comment here as well.
___
*[demo/index.html, line 133 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHEB98p0yZXiqecrfeo:-LHEB98p0yZXiqecrfep:bc4p2gw) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/07dbabf337f9e23b5880f4edb57db85a32dd1ea8/demo/index.html#L133)):*
> ```HTML
>             paragraph.innerText = 'The content of this overlay was generated with renderer';
>             btn.innerText = 'Close';
>             btn.addEventListener('click', () => root.opened = false);
> ```

We cannot guarantee that `root` is the overlay, so using the overlay APIs on the root should not be encouraged.

`overlay.opened = false` is better for this demo, I think, since we already have a reference to the overlay in the scope. Plus would be easier to read.
___
*[test/renderer.html, line 18 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHEBiiD1hNpQUWYWeu2:-LHEBiiE74DTHRIAiIzN:b-cp2r4v) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/07dbabf337f9e23b5880f4edb57db85a32dd1ea8/test/renderer.html#L18)):*
> ```HTML
>     <template>
>       <vaadin-overlay>
>         <template>
> ```

The tests here should also make sure it works even if the template was never assigned.

A typical usage case with renderers would be to omit templates altogether.

I suggest to add another fixture with an overlay without a template.
___
*[test/renderer.html, line 42 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHEC_dxE6qG7dzt6TDU:-LHEC_dxE6qG7dzt6TDV:bokxdtg) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/07dbabf337f9e23b5880f4edb57db85a32dd1ea8/test/renderer.html#L42)):*
> ```HTML
> 
>       it('should fallback to render content with Templatizer when renderer is not defined', () => {
>         expect(overlay.textContent.trim()).to.be.eql('overlay-content');
> ```

BTW Small non-blocking tip here and below: `eql` is deep already, the shallow assertion is `equal`.
See: http://www.chaijs.com/api/bdd/#method_equal VS http://www.chaijs.com/api/bdd/#method_eql

Another thing, “equal”  is a valid verb. We can omit `.be`, having only `to.equal` sounds even better to me (“If A equals B, ...”).

**Review by platosha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: all files reviewed, 4 unresolved discussions (waiting on @YuriyVaadin)

___
*[demo/index.html, line 118 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHE9UVIANW6gLkvKpwA:-LHEEfaOEkSt2-fErQGy:b-fial9g) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/07dbabf337f9e23b5880f4edb57db85a32dd1ea8/demo/index.html#L118)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`Show *the* overlay`, it’s the particular overlay.
</blockquote></details>

Not a blocker though.

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @platosha and @YuriyVaadin)

___
*[demo/index.html, line 105 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHE7Kl6CDDvneWHcg7Y:-LHHppO8CFune3eMJ1uZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/72a66b1503f8a4630ccbb3b160ba5c1c055ad700/demo/index.html#L105)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW nitpicking, but the wording could be simpler a bit.

By default, the overlay uses the content from its template using `Polymer.Templatize`.

Alternatively, the content can be provided using the `renderer` callback function. 

NOTE: When the `renderer` property is defined, the `<template>` content is not used.
</blockquote></details>

Done.
___
*[demo/index.html, line 112 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHE70qYAO-1QZW9SBGn:-LHHpr2U0A2vk-OxUl_o:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/72a66b1503f8a4630ccbb3b160ba5c1c055ad700/demo/index.html#L112)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Using both `<template>` and `.renderer` is not a typical use case. These are alternative ways of using the overlay, so let us not put them both in the same demo.
</blockquote></details>

Done.
___
*[demo/index.html, line 118 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHE9UVIANW6gLkvKpwA:-LHHpszz6Rdee7C_y3rj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/72a66b1503f8a4630ccbb3b160ba5c1c055ad700/demo/index.html#L118)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Not a blocker though.
</blockquote></details>

Done.
___
*[demo/index.html, line 124 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHEARZC1hZ1cyt0vKRN:-LHHqJB50nVWK2Uw1qdu:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/72a66b1503f8a4630ccbb3b160ba5c1c055ad700/demo/index.html#L124)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

We should definitely mention why we check the `firstChild` like this. Maybe describe that the renderer callback can be called multiple times with the same in the description, and make a small comment here as well.
</blockquote></details>

Done.
___
*[demo/index.html, line 133 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHEB98p0yZXiqecrfeo:-LHHqK0aACOCebjqzSTD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/72a66b1503f8a4630ccbb3b160ba5c1c055ad700/demo/index.html#L133)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

We cannot guarantee that `root` is the overlay, so using the overlay APIs on the root should not be encouraged.

`overlay.opened = false` is better for this demo, I think, since we already have a reference to the overlay in the scope. Plus would be easier to read.
</blockquote></details>

Done.
___
*[test/renderer.html, line 18 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHEBiiD1hNpQUWYWeu2:-LHHsavj3R_HELsnFHar:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/72a66b1503f8a4630ccbb3b160ba5c1c055ad700/test/renderer.html#L18)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

The tests here should also make sure it works even if the template was never assigned.

A typical usage case with renderers would be to omit templates altogether.

I suggest to add another fixture with an overlay without a template.
</blockquote></details>

Updated.
___
*[test/renderer.html, line 42 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHEC_dxE6qG7dzt6TDU:-LHHsbmw1uvQFHjRgtEv:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/72a66b1503f8a4630ccbb3b160ba5c1c055ad700/test/renderer.html#L42)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Small non-blocking tip here and below: `eql` is deep already, the shallow assertion is `equal`.
See: http://www.chaijs.com/api/bdd/#method_equal VS http://www.chaijs.com/api/bdd/#method_eql

Another thing, “equal”  is a valid verb. We can omit `.be`, having only `to.equal` sounds even better to me (“If A equals B, ...”).
</blockquote></details>

Updated.

**Review by platosha — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHICYkCEjtUCyYvRdMu:-LHICYkCEjtUCyYvRdMv:bb7u90w) (no related file):*
Could you, please, cover this with a test?

https://coveralls.io/builds/17970260/source?filename=src%2Fvaadin-overlay.html#L627

---

**Review by manolo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: all files reviewed, 2 unresolved discussions (waiting on @YuriyVaadin)

___
*[src/vaadin-overlay.html, line 225 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHWvn0uDOdyfZftYdiP:-LHWvn0uDOdyfZftYdiQ:bf4h9b6) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/85e7038c472609d2ad42291ea7d4eadd8b9379f5/src/vaadin-overlay.html#L225)):*
> ```HTML
>            * NOTE: The renderer callback can be called several times with previous content available
>            */
>           renderer: {
> ```

We need to document the parameters that receives the renderer when it's called, otherwise developer needs to figure out what is in each argument `this.renderer(this.content, this.model, this.owner);`

**Review by platosha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHICYkCEjtUCyYvRdMu:-LHX-HePEvmk0ftdCuUx:b-896fix) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Could you, please, cover this with a test?

https://coveralls.io/builds/17970260/source?filename=src%2Fvaadin-overlay.html#L627
</blockquote></details>

Done.

---
___
*[src/vaadin-overlay.html, line 148 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX-ON68iqMyX4YHfX8:-LHX-ON68iqMyX4YHfX9:b-ujm0a8) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/85e7038c472609d2ad42291ea7d4eadd8b9379f5/src/vaadin-overlay.html#L148)):*
> ```HTML
>      * ```
>      *
>      * ### Templating
> ```

BTW there is a textual section on how overlay templates work. It might make sense to add another one for the renderer feature too.

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @platosha and @YuriyVaadin)

___
*[src/vaadin-overlay.html, line 148 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX-ON68iqMyX4YHfX8:-LHX4xZ44xq42mErzbG_:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/85e7038c472609d2ad42291ea7d4eadd8b9379f5/src/vaadin-overlay.html#L148)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW there is a textual section on how overlay templates work. It might make sense to add another one for the renderer feature too.
</blockquote></details>

Updated.
___
*[src/vaadin-overlay.html, line 225 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHWvn0uDOdyfZftYdiP:-LHX4wXPB3JJiyhuCggK:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/85e7038c472609d2ad42291ea7d4eadd8b9379f5/src/vaadin-overlay.html#L225)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We need to document the parameters that receives the renderer when it's called, otherwise developer needs to figure out what is in each argument `this.renderer(this.content, this.model, this.owner);`
</blockquote></details>

Updated.

**Review by manolo — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

___
*[demo/index.html, line 109 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX72755wqqT22eAkyW:-LHX72755wqqT22eAkyX:bfimf1q) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/79ff1217eb1d7f1acb42dc59fac6c86042019396/demo/index.html#L109)):*
> ```HTML
>     </p>
>     <p>
>       <strong>NOTE:</strong> When the renderer property is defined, the <code>&lt;template&gt;</code> content is not used.
> ```

This is already documented in the component, I don't think it adds any extra value in the demo. Not a blocker.

**Review by platosha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: all files reviewed, 4 unresolved discussions (waiting on @YuriyVaadin)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX70SU4JJH8aGVKrWF:-LHX70SU4JJH8aGVKrWG:b1nn7qj) (no related file):*
Nit: would be nice to update `analysis.json` now that the API docs have changes.

---
___
*[src/vaadin-overlay.html, line 175 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX6_6FB5Lz3WS8DZ_7:-LHX6_6GAieW5kI40Zbc:b-75i791) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/79ff1217eb1d7f1acb42dc59fac6c86042019396/src/vaadin-overlay.html#L175)):*
> ```HTML
>      * of the host element by accessing `owner`.
>      *
>      * NOTE when the renderer property is defined, the `<template>` content is not used.
> ```

Nit: Please make `**NOTE:**` bold.
___
*[src/vaadin-overlay.html, line 176 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX6dYV7qYFQg0yY3aO:-LHX6dYV7qYFQg0yY3aP:bbtugve) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/79ff1217eb1d7f1acb42dc59fac6c86042019396/src/vaadin-overlay.html#L176)):*
> ```HTML
>      *
>      * NOTE when the renderer property is defined, the `<template>` content is not used.
>      * NOTE renderer function could be called several times, so it is a good practise to
> ```

Nit: NOTEs should be separate paragraphs. Please add an empty line between them.

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @manolo, @platosha, and @YuriyVaadin)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX70SU4JJH8aGVKrWF:-LHX8Nri6tocIlUEQsqQ:b-896fix) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Nit: would be nice to update `analysis.json` now that the API docs have changes.
</blockquote></details>

Done.

---
___
*[demo/index.html, line 109 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX72755wqqT22eAkyW:-LHX8PT2ES_qvikViJL3:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/79ff1217eb1d7f1acb42dc59fac6c86042019396/demo/index.html#L109)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This is already documented in the component, I don't think it adds any extra value in the demo. Not a blocker. 
</blockquote></details>

Removed.
___
*[src/vaadin-overlay.html, line 175 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX6_6FB5Lz3WS8DZ_7:-LHX8QaL7WqL7jXFJOUq:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/79ff1217eb1d7f1acb42dc59fac6c86042019396/src/vaadin-overlay.html#L175)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Nit: Please make `**NOTE:**` bold.
</blockquote></details>

Updated.
___
*[src/vaadin-overlay.html, line 176 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-LHX6dYV7qYFQg0yY3aO:-LHX8RoTEVRVOqKS5J0P:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/79ff1217eb1d7f1acb42dc59fac6c86042019396/src/vaadin-overlay.html#L176)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Nit: NOTEs should be separate paragraphs. Please add an empty line between them.
</blockquote></details>

Updated.

**Review by manolo — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96#-:-LHX9SSzEz2pdrSZpr-H:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @platosha)

**Review by platosha — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/96)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
