### PR TITLE
Args order

### PR DESCRIPTION
**Pull request by yuriy-fix**
Connected to https://github.com/vaadin/components-team-tasks/issues/382

Change renderer args order to `root, owner, model`

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/98)

### CODE REVIEW

**Review by platosha — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/98)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by platosha — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/98)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by platosha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/98)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

___
*[analysis.json, line 92 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/98#-LHbZcgWDqhVodie6bqc:-LHbZcgWDqhVodie6bqd:b12u8zt) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/a9c5c41e09ba3ed8101ae2bfe02e53ff4a6f4079/analysis.json#L92)):*
> ```JSON
>               "name": "renderer",
>               "type": "Function | null | undefined",
>               "description": "Custom function for rendering the content of the overlay.\nReceives arguments `root`, `model`, `owner`\n\n`root` The root container element. Users are able to append content to it.\n\n`owner` The host element of the renderer function.\n\n`model` Object with properties that could be required during the rendering process.\n\n**NOTE:** The renderer callback can be called several times with previous content available",
> ```

Description in the analysis still lists as `root`, `model`, `owner`. Maybe needs one more analysis update.

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/98)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @platosha and @YuriyVaadin)

___
*[analysis.json, line 92 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/98#-LHbZcgWDqhVodie6bqc:-LHcFyPr-G-QmCSfSw8D:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/a9c5c41e09ba3ed8101ae2bfe02e53ff4a6f4079/analysis.json#L92)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Description in the analysis still lists as `root`, `model`, `owner`. Maybe needs one more analysis update.
</blockquote></details>

Updated.

**Review by manolo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/98#-:-LHfzEn7AmsIhoTzWWRv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @platosha)

**Review by platosha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/98#-:-LHglR5NA9fETZQ4ZT1u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
