### PR TITLE
Focus sequence is broken by focusing with mouse. Fix #53

### LINKED ISSUE #53: When focusTrap is active, focusing with mouse breaks focus sequence
The problem is that memoized `this._focusedElement` is only updated when focusing with tabs.

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/59)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-overlay.html, line 467 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59#-L5NqeTgdq3qN6u4cQ3j:-L5NqeTgdq3qN6u4cQ3k:bofnlxy) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/96fcce93b8d09297e3e2a5701d0c2402a7c990f5/src/vaadin-overlay.html#L467)):*
> ```HTML
>         const focusableElements = this._getFocusableElements();
> 
>         if (!this._isFocused(this._focusedElement)) {
> ```

Way complicated.

This is a keyboard event listener. Naturally, keyboard events are dispatched on the focused elements only.

`this._focusedElement = event.composedPath()[0];` should work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59#-L5Nryqk5bEU2TRKppPd:-L5Nryqk5bEU2TRKppPe:b-buo2) (no related file):*
Can this be tested?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59)*

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-overlay.html, line 467 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59#-L5NqeTgdq3qN6u4cQ3j:-L5NrTlYtJLmfDP19HEF:bnaavqo) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/96fcce93b8d09297e3e2a5701d0c2402a7c990f5/src/vaadin-overlay.html#L467)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Way complicated.

This is a keyboard event listener. Naturally, keyboard events are dispatched on the focused elements only.

`this._focusedElement = event.composedPath()[0];` should work.
</blockquote></details>

OK actually, I’ve realised that `event.composedPath()[0]` might not work for ControlStateMixin’s <kbd>Shift</kbd>+<kbd>Tab</kbd> handling.

Not a blocker. Another option is to iterate deep shadow roots starting from `this.getRootNode().activeElement`  for that. I doubt that there is any noticeable difference though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59#-L5Nryqk5bEU2TRKppPd:-L5SuLepwJVwEynbb0rY:byz6l0i) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Can this be tested?
</blockquote></details>

I guess only, adding a flaky test. Every test related with focus  and activeElement has  caused more problems than advantages. I think by mocking all things in the code it might work, but probably too complex. Will spend some time though

---

*[src/vaadin-overlay.html, line 467 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59#-L5NqeTgdq3qN6u4cQ3j:-L5Sv5hrZWO0-hngNzTG:bv5nju0) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/96fcce93b8d09297e3e2a5701d0c2402a7c990f5/src/vaadin-overlay.html#L467)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK actually, I’ve realised that `event.composedPath()[0]` might not work for ControlStateMixin’s <kbd>Shift</kbd>+<kbd>Tab</kbd> handling.

Not a blocker. Another option is to iterate deep shadow roots starting from `this.getRootNode().activeElement`  for that. I doubt that there is any noticeable difference though.
</blockquote></details>

I checked other options, but this seemed the simplest and apparently working in all  sceneries 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59#-L5Nryqk5bEU2TRKppPd:-L5wm1Ph-tL3f6e_-kgn:bykifh9) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I guess only, adding a flaky test. Every test related with focus  and activeElement has  caused more problems than advantages. I think by mocking all things in the code it might work, but probably too complex. Will spend some time though
</blockquote></details>

@tomivirkki  Added the test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59#-:-L61G5-hHNotmMPdJber:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/59#-:-L61IuNarr2rXo5dAP7j:bnfp4nl)*

**Pull request merged**
