### PR TITLE
Remove this._placeholder usage

### LINKED ISSUE #80: Overlay is throwing exception when toggling it quickly
```
Uncaught TypeError: Cannot read property 'insertBefore' of null
    at HTMLElement._detachOverlay (vaadin-overlay.html:430)
    at HTMLElement.listener (vaadin-overlay.html:417)
_detachOverlay @ vaadin-overlay.html:430
listener @ vaadin-overlay.html:417
```

Live demo: https://cdn.vaadin.com/vaadin-dropdown-menu/1.0.0-beta3/demo/#dropdown-menu-basic-demos

peek 2018-04-18 10-19

Steps to reproduce:

- focus any dropdown-menu
- quickly press <kbd>Space</kbd> several times

### PR DESCRIPTION
**Pull request by limonte**
Fixes #80

The test suites are in vaadin/vaadin-dropdown-menu#116

For better CR experience, please use `?w=1`: https://github.com/vaadin/vaadin-overlay/pull/85/files?w=1

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/85)

### CODE REVIEW

**Comment by limonte** [comment]
The build is failing because of stylelint, related PR: https://github.com/vaadin/stylelint-config-vaadin/pull/2

**Comment by limonte** [comment]
After https://github.com/vaadin/vaadin-date-picker/pull/542 has been merged, the build is green and the PR is ready for review.

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-overlay.html, line 476 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/85#-LBLB9PY4gixBsIY3jjX:-LBLB9PY4gixBsIY3jjY:b-m8x6uf) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/54711036c7b7371c423ac57f076893b3641482a2/src/vaadin-overlay.html#L476)):*
> ```HTML
> 
>       _detachOverlay() {
>         // The detaching overlay is happening after closing animation is finished.
> ```

The source code doesn't need long explanations like this if the element is tested properly. Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/85#-:-LBLBlvuCtKiF0XdVTUm:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/85)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/85#-:-LBLJWxSCMsROlabf9-L:bnfp4nl)*

**Pull request merged**
