### PR TITLE
Call render when overlay first time opened

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes https://github.com/vaadin/vaadin-dialog/issues/108

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/120)

### CODE REVIEW

**Review by samiheikki — COMMENTED** [review]
`should use content part shadowRoot for contents when initially opened in component scope` test is not passing. @tomivirkki do you know a possible fix for it? I did not fully understood what the test case was trying to test.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/120#-:-LLP4G588znP0usqxDYN:bxie3hs)* status: 0 of 3 files reviewed, all discussions resolved

**Review by tomivirkki — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/120)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @samiheikki and @tomivirkki)

___
*[test/renderer.html, line 101 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/120#-LLTZSiSA-0h3UIayUus:-LLTZSiSA-0h3UIayUut:b-ehwzu0) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/4705ed855f1d58d5166782869095ad8979e134f0/test/renderer.html#L101)):*
> ```HTML
>           const spy = sinon.spy();
>           overlay.renderer = () => spy();
>           overlay.template = null;
> ```

We should open the overlay before changing the template here. The "if (opened)" check alone will otherwise make sure the spy doesn't get called.
___
*[test/renderer.html, line 109 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/120#-LLTZxXW7yGOE_JwBEHA:-LLTZxXW7yGOE_JwBEHB:b-ya81ng) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/4705ed855f1d58d5166782869095ad8979e134f0/test/renderer.html#L109)):*
> ```HTML
>           overlay.renderer = () => spy();
>           overlay.opened = true;
>           overlay.model = {};
> ```

Same as above
___
*[test/renderer.html, line 110 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/120#-LLTZ3Yg4CmgL-x0S5mV:-LLTZ3Yg4CmgL-x0S5mW:b-iwtl6) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/4705ed855f1d58d5166782869095ad8979e134f0/test/renderer.html#L110)):*
> ```HTML
>           overlay.opened = true;
>           overlay.model = {};
>           expect(spy.calledTwice).to.be.true;
> ```

This calledTwice assertion is strange imo. If we're testing what the title says "should call renderer on model change" then it would be cleaner to reset the spy before the model change and assert that the spy got called (once) afterwards

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/120)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @samiheikki)

___
*[test/renderer.html, line 101 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/120#-LLTZSiSA-0h3UIayUus:-LLTdfnh8KnSQEUP6BZJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/4705ed855f1d58d5166782869095ad8979e134f0/test/renderer.html#L101)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We should open the overlay before changing the template here. The "if (opened)" check alone will otherwise make sure the spy doesn't get called.
</blockquote></details>

Done.
___
*[test/renderer.html, line 109 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/120#-LLTZxXW7yGOE_JwBEHA:-LLTdgX7EAr3bcPlCu4W:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/4705ed855f1d58d5166782869095ad8979e134f0/test/renderer.html#L109)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[test/renderer.html, line 110 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/120#-LLTZ3Yg4CmgL-x0S5mV:-LLTdi-F9JmIhBtjK-se:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/4705ed855f1d58d5166782869095ad8979e134f0/test/renderer.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This calledTwice assertion is strange imo. If we're testing what the title says "should call renderer on model change" then it would be cleaner to reset the spy before the model change and assert that the spy got called (once) afterwards
</blockquote></details>

Done.

**Review by tomivirkki — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/120#-:-LLTg83g2iuWe-jLf5Qn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by web-padawan — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/120)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
