### PR TITLE
Fix renderer observer, avoid unnecessary template restamp

### PR DESCRIPTION
**Pull request by platosha**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/99)

### CODE REVIEW

**Review by manolo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/99#-:-LHfzdLG78I67_nRHUOC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yuriy-fix — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/99)* status: all files reviewed, 1 unresolved discussion (waiting on @platosha)

___
*[src/vaadin-overlay.html, line 738 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/99#-LHgL8WO6IoLFV4TLWvZ:-LHgL8WO6IoLFV4TLWv_:brhykqb) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/70d3e761b54ad4f14b725d73327788b8aacf2a92/src/vaadin-overlay.html#L738)):*
> ```HTML
>         if (oldRenderer && !renderer) {
>           // Renderer was removed, restore the template
>           this._templateChanged(this.template);
> ```

I guess we can update it not to call `observer`, but instead expose a function from it which can be called here.
Not a blocker as not fully a part of this PR.

**Review by platosha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/99)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin and @manolo)

___
*[src/vaadin-overlay.html, line 738 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/99#-LHgL8WO6IoLFV4TLWvZ:-LHgVbLs0sdCq0QwtuKV:bs7wumx) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/70d3e761b54ad4f14b725d73327788b8aacf2a92/src/vaadin-overlay.html#L738)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

I guess we can update it not to call `observer`, but instead expose a function from it which can be called here.
Not a blocker as not fully a part of this PR.
</blockquote></details>

Done.

**Review by yuriy-fix — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/99#-:-LHgrd6z4FY47KEZtl2I:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by manolo — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/99)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
