### PR TITLE
Enable styling the overlay content from parent scope

### PR DESCRIPTION
**Pull request by platosha**
Connected to #75

This is mainly a discussion opener at the moment. Let us focus on the overall
approach first.

Once the approach is agreed, I can polish it with prettier code more tests.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/76)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Works nice. There are some unavoidable limitations but this really improves the overall stylability of the overlay contents.

**Comment by jouni** [comment]
The demo won’t open the overlay on Safari. Works in Chrome and Firefox.

**Comment by jouni** [comment]
Also, just for the record – I really like this enhancement 👍 Makes styling much easier and predictable for the developer.

**Comment by limonte** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[demo/index.html, line 52 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-LACR6qEAQ4DTSLGMdqM:-LACR6qEAQ4DTSLGMdqN:bccff8x) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/a2c4a1dad4043d3d1f9d005d54e4962e74c667c4/demo/index.html#L52)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Show and Hide Overlay with backdrop and focus trap</h3>
> ```

The "Show and Hide Overlay with backdrop and focus trap" example is currently broken:

 
`VM160:7 Uncaught TypeError: Cannot read property 'focus' of null`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76)*

**Comment by yuriy-fix** [comment]
Reviewed 2 of 6 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76)*

**Comment by platosha** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 52 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-LACR6qEAQ4DTSLGMdqM:-LACVRzd52w0tUzyGtfv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/a2c4a1dad4043d3d1f9d005d54e4962e74c667c4/demo/index.html#L52)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

The "Show and Hide Overlay with backdrop and focus trap" example is currently broken:

 
`VM160:7 Uncaught TypeError: Cannot read property 'focus' of null`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-:-LACWdY89xnGD4vulgB_:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 559 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-LACtFUwAl9in_qY45Op:-LACtFUwAl9in_qY45Oq:bp1tddy) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/92cccb1266ec3a3754e03f90e1c56c9c8a4a0dde/src/vaadin-overlay.html#L559)):*
> ```HTML
>       }
> 
>       _templateChanged(template) {
> ```

Should the template-element be removed from the overlay light DOM now that the stamped content is added to the light DOM also? Here's how it looks like: https://www.dropbox.com/s/qqczpkj43dt17uz/Screenshot%202018-04-16%2012.57.11.png?dl=0

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-overlay.html, line 559 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-LACtFUwAl9in_qY45Op:-LACuV4sBdlQZXaZhhYF:b-qpuw4e) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/92cccb1266ec3a3754e03f90e1c56c9c8a4a0dde/src/vaadin-overlay.html#L559)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should the template-element be removed from the overlay light DOM now that the stamped content is added to the light DOM also? Here's how it looks like: https://www.dropbox.com/s/qqczpkj43dt17uz/Screenshot%202018-04-16%2012.57.11.png?dl=0
</blockquote></details>

This is kind of expected, isn’t it?

And it doesn’t make a big difference, aprat from affecting selectors such as `:first-child`, the template contents are naturally isolated anyway.

I don’t have a good reason for removing, while not removing is less work. WDYT?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-overlay.html, line 559 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-LACtFUwAl9in_qY45Op:-LACw84rEGI4IsWnFGF7:b5p5zya) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/92cccb1266ec3a3754e03f90e1c56c9c8a4a0dde/src/vaadin-overlay.html#L559)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This is kind of expected, isn’t it?

And it doesn’t make a big difference, aprat from affecting selectors such as `:first-child`, the template contents are naturally isolated anyway.

I don’t have a good reason for removing, while not removing is less work. WDYT?
</blockquote></details>

Plus, there is a workaround if this is troublesome for anyone, users can assign it to `.template` and keep the actual template elsewhere outside,

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76)*

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 559 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-LACtFUwAl9in_qY45Op:-LACwyzj04RLnDTVZHlX:b-gv2d8s) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/92cccb1266ec3a3754e03f90e1c56c9c8a4a0dde/src/vaadin-overlay.html#L559)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Plus, there is a workaround if this is troublesome for anyone, users can assign it to `.template` and keep the actual template elsewhere outside,
</blockquote></details>

Ok, I guess it's not that big a problem to have it there.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-:-LACxmHMCFuxT3bX5Hxc:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-overlay.html, line 127 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-LACsMTFEw_8sz_rpLHa:-LACsMTFEw_8sz_rpLHb:b-fnzft1) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/92cccb1266ec3a3754e03f90e1c56c9c8a4a0dde/src/vaadin-overlay.html#L127)):*
> ```HTML
>      *
>      * - If the overlay is used in a component, then the component styles
>      *   apply the overlay content.
> ```

BTW missing "to" (apply to the overlay content)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-:-LACy9-H-UQwfsxQG9n0:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r1, 6 of 7 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/76#-:-LAD0qiw0s7BCtxp5tes:bnfp4nl)*

**Pull request merged**
