### PR TITLE
Remove onclick from demos.

### LINKED ISSUE #109: Remove onclick listener from demos
Remove onclick listener from demos where the JS counterpart is available.

### PR DESCRIPTION
**Pull request by sohrabtaee**
Fixes #109

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/110)

### CODE REVIEW

**Review by web-padawan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/110)* status: all files reviewed, 2 unresolved discussions (waiting on @sohrabtaee)

___
*[demo/index.html, line 192 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/110#-LJTcfr30UdRPSZ0WtGE:-LJTcfr30UdRPSZ0WtGF:b-jswe4k) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/dfb38b69394d544167e21c80c3944cf5a0c47bb6/demo/index.html#L192)):*
> ```HTML
>               root.textContent = 'I am next to the pointer';
>             };
>             overlayPointer.style =
> ```

not related to this PR (was done earlier) but while you are here, please fix to set attribute:
```
overlayPointer.setAttribute(
  'style',
  'left: ' + event.clientX + 'px;' +
  'top: ' + event.clientY + 'px;' +
  'align-items: flex-start; justify-content: flex-start;'
);
```

this is needed by IE11
___
*[demo/index.html, line 209 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/110#-LJTcsk3EU4ai4njO1A6:-LJTcsk3EU4ai4njO1A7:bjptg75) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/dfb38b69394d544167e21c80c3944cf5a0c47bb6/demo/index.html#L209)):*
> ```HTML
>             };
>             var rect = event.target.getBoundingClientRect();
>             overlayBelow.style =
> ```

not related to this PR (was done earlier) but while you are here, please fix to set attribute:
```
overlayBelow.setAttribute(
  'style',
  'top: ' + rect.bottom + 'px;' +
  'left: ' + rect.left + 'px;' +
  'right: ' + (document.documentElement.clientWidth - rect.right) + 'px;' +
  'align-items: stretch; justify-content: flex-start;'
);
```

this is needed by IE11

**Review by manolo — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/110)* status: all files reviewed, 2 unresolved discussions (waiting on @sohrabtaee)

**Review by yuriy-fix — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/110)* status: all files reviewed, 2 unresolved discussions (waiting on @sohrabtaee)

**Review by sohrabtaee — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/110)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @YuriyVaadin, @manolo, and @web-padawan)

___
*[demo/index.html, line 192 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/110#-LJTcfr30UdRPSZ0WtGE:-LJXe4IW2yBbEcN9GTpW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/dfb38b69394d544167e21c80c3944cf5a0c47bb6/demo/index.html#L192)):*
<details><summary><i>Previously, web-padawan (Serhii Kulykov) wrote…</i></summary><blockquote>

not related to this PR (was done earlier) but while you are here, please fix to set attribute:
```
overlayPointer.setAttribute(
  'style',
  'left: ' + event.clientX + 'px;' +
  'top: ' + event.clientY + 'px;' +
  'align-items: flex-start; justify-content: flex-start;'
);
```

this is needed by IE11
</blockquote></details>

Done.
___
*[demo/index.html, line 209 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/110#-LJTcsk3EU4ai4njO1A6:-LJXe4jiBJ2OCUIN8Hl8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/dfb38b69394d544167e21c80c3944cf5a0c47bb6/demo/index.html#L209)):*
<details><summary><i>Previously, web-padawan (Serhii Kulykov) wrote…</i></summary><blockquote>

not related to this PR (was done earlier) but while you are here, please fix to set attribute:
```
overlayBelow.setAttribute(
  'style',
  'top: ' + rect.bottom + 'px;' +
  'left: ' + rect.left + 'px;' +
  'right: ' + (document.documentElement.clientWidth - rect.right) + 'px;' +
  'align-items: stretch; justify-content: flex-start;'
);
```

this is needed by IE11
</blockquote></details>

Done.

**Review by web-padawan — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/110#-:-LJXgilm7009MpxpqKuF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by manolo — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/110#-:-LJXiSF19ipvo8UsoaQr:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by web-padawan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/110)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
