### PR TITLE
Fix multiple overlays and default value for opened property

### LINKED ISSUE #129: Vaadin combo box overlay with two dialog overlays can cause close on click inside
Hello,

Given two open vaadin dialogs and there is a comb box inside the second one. When I open the combo box, close it, then click anywhere on the second dialog, the dialog will determine the click as an outside click and will be closed.

Code to reproduce:

```html
<vaadin-dialog id="dialog1" opened>
    <template>
        Dialog1
    </template>
</vaadin-dialog>

<vaadin-dialog id="dialog2" opened>
    <template>
        <vaadin-combo-box items='["1", "2"]'>
        </vaadin-combo-box>
        <br>
        Open the combo box, close it, then click here!
    </template>
</vaadin-dialog>
```

Available in this link: https://jsfiddle.net/dwtkbgf6

Versions:
 - vaadin-overlay: 3.1.1
 - vaadin-dialog: 2.1.0
 - vaadin-combo-box: 4.1.0

I think this pr caused the problem: https://github.com/vaadin/vaadin-overlay/pull/115
Downgrading to 3.1.0-beta2 solves the problem.

Thanks,
István

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #129 

The implementation of multiple overlays is actually correct, but there is one side effect caused by default `opened` value in `vaadin-combo-box` set to `false`: https://github.com/vaadin/vaadin-combo-box/blob/96584b5d0451262a886817acc4bea7a8f969cd19/src/vaadin-combo-box-mixin.html#L32

Stamping the dialog with the combo-box inside it forced the `_exitModalState` to happen, and messed up the attached instances, so that incorrect weird things started to happen.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/130)

### CODE REVIEW

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/130)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-overlay/130#-LOx7CP15AS-tQuGkIWs:-LOx7CP15AS-tQuGkIWt:b-y8toqs) (no related file):*
Looks like this fix is not enough, as the combo-box overlay now stays under the body. Investigating.

---

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/130)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-overlay/130#-LOx7CP15AS-tQuGkIWs:-LOxCO3m2fY_nDoAMJR1:b-qjtvz6) (no related file):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Looks like this fix is not enough, as the combo-box overlay now stays under the body. Investigating.
</blockquote></details>

Changed to use single property observer, now it should work (missed it previously).

---

**Review by limonte — CHANGES_REQUESTED** [review]
I'm experiencing this unwanted behavior, not sure if it's in scope of #129 and this PR

combo-box

(I'm using the code snippet provided in #129)

**Review by web-padawan — COMMENTED** [review]
Confirmed. Taking a look now

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/130#-:-LP02_b7-tUJM1rPb3bB:blrz1us)* status: 0 of 4 files reviewed, 1 unresolved discussion

**Review by web-padawan — COMMENTED** [review]
Looks like the `reverse()` is not needed, as we use`instances.pop()` which picks the overlay from the end of the reversed array (which means, not the last one, but the 1st instance). Will improve tests to handle that.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/130#-:-LP07CgTAlBZAwZrvJjS:b-k1xkny)* status: 0 of 4 files reviewed, 1 unresolved discussion

**Comment by web-padawan** [comment]
@limonte should be fixed now, PTAL

**Review by limonte — APPROVED** [review]

**Review by tomivirkki — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/130#-:-LP50elY0_Et1eP2mvuo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by web-padawan** [comment]
Cherry-picked and pushed to `3.1` branch: https://github.com/vaadin/vaadin-overlay/tree/3.1

**Pull request merged**
