### PR TITLE
Skip focus operations if focusTrap is not set

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/vaadin-combo-box/issues/519

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/24)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/vaadin-overlay.html, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24#-Ku-9cJv_Gr2klU93z1t:-Ku-9cJv_Gr2klU93z1u:bnu26f5) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/da75cd758aef5af24e626a24eb2842f2fc039424/test/vaadin-overlay.html#L33)):*
> ```HTML
>   </test-fixture>
> 
>   <test-fixture id="empty">
> ```

it's not empty, there's one textNode. Maybe `"no-focusable-elements-inside"`?

---

*[test/vaadin-overlay.html, line 128 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24#-Ku-AHqJTDU779TtnUJW:-Ku-AHqJTDU779TtnUJX:bn1kyky) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/da75cd758aef5af24e626a24eb2842f2fc039424/test/vaadin-overlay.html#L128)):*
> ```HTML
>         });
> 
>         describe('empty content', function() {
> ```

it's not empty, the better name would be `'content without focusable elements'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24#-:-Ku-DzqJgFfUPcZbr6Z4:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/vaadin-overlay.html, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24#-Ku-9cJv_Gr2klU93z1t:-Ku-F9v8dhwFHtzLC3Wd:bc7ar29) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/da75cd758aef5af24e626a24eb2842f2fc039424/test/vaadin-overlay.html#L33)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

it's not empty, there's one textNode. Maybe `"no-focusable-elements-inside"`?
</blockquote></details>

Removing the textContent, actually it's not used in the test

---

*[test/vaadin-overlay.html, line 128 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24#-Ku-AHqJTDU779TtnUJW:-Ku-FFQDsWCLZKp0esd5:b-41z7nb) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/da75cd758aef5af24e626a24eb2842f2fc039424/test/vaadin-overlay.html#L128)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

it's not empty, the better name would be `'content without focusable elements'`
</blockquote></details>

Removed all the content, 'empty content' makes sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24)*

**Comment by limonte** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/24#-:-Ku-JHeG3J-_loSvDaQd:bnfp4nl)*

**Pull request merged**
