### PR TITLE
Handle backdrop click as outside-click

### PR DESCRIPTION
**Pull request by limonte**
Connected to https://github.com/vaadin/vaadin-overlay/pull/5

Answering my own question :)

> will this solution work for both cases: with and without backdrop?

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/8)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-overlay.html, line 161 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/8#-KqcEE8LJR1PbV8rXPHc:-KqcEE8LJR1PbV8rXPHd:bjw5s5i) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/208f549bfeee807e467079f35c6829ed09628180/vaadin-overlay.html#L161)):*
> ```HTML
>         this.dispatchEvent(evt);
> 
>         if (this.opened && event.composedPath().indexOf(this) < 0 && !evt.defaultPrevented) {
> ```

Why is this removed? Now we can't click the overlay content without closing it. Maybe it would work if it was changed to `this.$.content`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/8)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-overlay.html, line 161 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/8#-KqcEE8LJR1PbV8rXPHc:-KqcJmdAtxWSW5zMIkNH:b2qp7y5) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/208f549bfeee807e467079f35c6829ed09628180/vaadin-overlay.html#L161)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this removed? Now we can't click the overlay content without closing it. Maybe it would work if it was changed to `this.$.content`?
</blockquote></details>

Exactly, thanks! Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/8)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/8#-:-KqcLlUL_UO5QC6n1ZYc:bnfp4nl)*

**Comment by yuriy-fix** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/8#-:-Kqd5lFGzpHgzmQK3I3S:bg7igkv)*

**Pull request merged**
