### PR TITLE
Set withBackdrop default to false

### PR DESCRIPTION
**Pull request by yuriy-fix**
Changing withBackdrop default to false, add demo and test

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/7)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Rebase and run analysis

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7#-KqWx9odNruf_nb560H-:-KqWx9oejaUFr2yWSgmJ:b-j6aw94) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/96f8cd4b5030d9ba2ee3a68ea595f5034596d6d4/demo/index.html#L36)):*
> ```HTML
>     <demo-snippet>
>       <template>
>         <vaadin-overlay with-backdrop="true" id="overlay2">
> ```

just "with-backdrop"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7#-:-KqWxEGb1wo9ynRCp1Gr:bprebwx)*

**Comment by yuriy-fix** [comment]
Rebased and analysis updated.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7#-KqWx9odNruf_nb560H-:-KqX8fDcdehmgwMuR8Ji:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/96f8cd4b5030d9ba2ee3a68ea595f5034596d6d4/demo/index.html#L36)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

just "with-backdrop"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7#-:-KqX8gH4cdl1YZFH8M5g:b-wob3uf)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7#-:-KqXQ9YiqXjLKbH5kBNy:bnfp4nl)*

**Comment by limonte** [comment]
The last example will look better with backdrop. Otherwise :lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7#-:-KqXQHuUsAbLfb-jlvrI:b-r0khyh)*

**Comment by yuriy-fix** [comment]
Changed in last example.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7#-:-KqXRV9Eg249eji1yyYt:b-luomsc)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7)*

**Comment by limonte** [comment]
Reviewed 3 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/7)*

**Pull request merged**
