### PR TITLE
Update demos to prefer renderers

### LINKED ISSUE #105: Update demos to prefer renderers
Child of vaadin/components-team-tasks#386

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fixes #105

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107)

### CODE REVIEW

**Review by web-padawan — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[demo/index.html, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-LIeKdzb6Bj0lrVDPP8n:-LIeKdzb6Bj0lrVDPP8o:balmrw8) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f39876c131adf49f7e576675605031fe866e11a5/demo/index.html#L27)):*
> ```HTML
>           Show overlay
>         </vaadin-button>
>         <script>
> ```

BTW now when we have the script tag anyways, there is no need to use the "onclick" attribute in this demo, same for "Modeless (Non-Modal) Overlay"
___
*[demo/index.html, line 85 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-LIeLJ-_4R-AD9-9lQbH:-LIeLJ-_4R-AD9-9lQbI:b-20a6mb) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f39876c131adf49f7e576675605031fe866e11a5/demo/index.html#L85)):*
> ```HTML
>           overlayFocusTrapBackdrop.renderer = function(root) {
>             root.innerHTML =
>             '<h3>Focus is trapped inside the content block</h3>' +
> ```

BTW this line should be aligned with the lines below

**Comment by sohrabtaee** [comment]
___
*[demo/index.html, line 28 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-LIfBvcw6CmXgBM_I1ei:-LIfBvcw6CmXgBM_I1ej:b-xik60c) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f39876c131adf49f7e576675605031fe866e11a5/demo/index.html#L28)):*
> ```HTML
>         </vaadin-button>
>         <script>
>           var overlay1 = document.querySelector('#overlay1');
> ```

Nit: you can remove 1 from variable name and use `const` instead of `var`.

**Review by web-padawan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

___
*[demo/index.html, line 28 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-LIfBvcw6CmXgBM_I1ei:-LIpWlVV3zXwtqKC3Kvg:bdv78t) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f39876c131adf49f7e576675605031fe866e11a5/demo/index.html#L28)):*
<details><summary><i>Previously, sohrabtaee (Sohrab Taee) wrote…</i></summary><blockquote>

Nit: you can remove 1 from variable name and use `const` instead of `var`.
</blockquote></details>

For some reason it only works with var. Looks like demo snippets used here are not processed like they should, but this is anyways internal component so it does not block us.

**Review by web-padawan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-:-LIpWx-d8_JTgtPi-7l1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sohrabtaee — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by manolo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

___
*[demo/index.html, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-LIeKdzb6Bj0lrVDPP8n:-LIpddft5iyJJuM-jQys:b5ppp02) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f39876c131adf49f7e576675605031fe866e11a5/demo/index.html#L27)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW now when we have the script tag anyways, there is no need to use the "onclick" attribute in this demo, same for "Modeless (Non-Modal) Overlay"
</blockquote></details>

good point, it's easier for developer to see what the button does in code. Let's take do in this PR pls

**Review by manolo — COMMENTED** [review]
CI is failing with the error 'Couldn't find any versions for "@vaadin/vaadin-button" that matches "^2.0.0"'  you need to fix bower deps

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-:-LIpeUHr6NamZSD240ke:b3mdkql)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

**Review by yuriy-fix — COMMENTED** [review]
Updated.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-:-LItT1SnBasJuM9XBB4G:b-bw8e14)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @manolo and @web-padawan)

___
*[demo/index.html, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-LIeKdzb6Bj0lrVDPP8n:-LItSQf4EIjki60hWa6C:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f39876c131adf49f7e576675605031fe866e11a5/demo/index.html#L27)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

good point, it's easier for developer to see what the button does in code. Let's take do in this PR pls
</blockquote></details>

Done.
___
*[demo/index.html, line 85 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-LIeLJ-_4R-AD9-9lQbH:-LItSyv173x8hAHuqVms:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/f39876c131adf49f7e576675605031fe866e11a5/demo/index.html#L85)):*
<details><summary><i>Previously, web-padawan (Serhii Kulykov) wrote…</i></summary><blockquote>

BTW this line should be aligned with the lines below
</blockquote></details>

Done.

**Review by web-padawan — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107)* status: all files reviewed, 1 unresolved discussion (waiting on @manolo)

**Review by manolo — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107#-:-LItTyI2790ludA1ZDc_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @manolo)

**Review by manolo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/107)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
