### PR TITLE
Focus trap: sort focusable elements by tabindex

### PR DESCRIPTION
**Pull request by limonte**
Connected to #15 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/16)

### CODE REVIEW

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/16#-:-KrixHieOFjvDPF7vX6R:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-overlay.html, line 228 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/16#-KriyIODTRQ8vQLHVJS6:-KriyIODTRQ8vQLHVJS7:b2omlbl) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/1df5717e24af5afa76b17a776a26317bb8640c74/vaadin-overlay.html#L228)):*
> ```HTML
>           document.body.style.pointerEvents = 'none';
> 
>           Polymer.Async.idlePeriod.run(() => {
> ```

What does this mean? Can't we fire the event synchronously?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/16)*

**Comment by manolo** [comment]
Do we actually need code  dealing with focus and tabindex in dialog? 
Dialog only should take care that the dialog itself is focused when opened, but it shouldn't figure out what is the most appropriate element to focus.
I think it's user responsability to move the focus to the appropriate control inside the dialog, for instance cancel button, etc.
Probably adding a hidden input  with a -1 tabindex and focusing it when dialog is opened is enough and will leave simple code in the element

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/16#-:-Krixt5JC5fkvPxOKhj7:b-s8xho4)*

**Comment by limonte** [comment]
We absolutely need to handle focusable elements inside the dialog. Dialog is not just a div with a backdrop.

> I think it's user responsability to move the focus to the appropriate control inside the dialog, for instance cancel button, etc.

I disagree, it's the responsibility of a dialog.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-overlay.html, line 228 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/16#-KriyIODTRQ8vQLHVJS6:-Krj0t7qYR5nWN1S7Mx1:b-2nbk4e) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/1df5717e24af5afa76b17a776a26317bb8640c74/vaadin-overlay.html#L228)):*
> Polymer.Async.idlePeriod

This is a wrapper for [requestIdleCallback](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback). Event can't be fired synchronously as focus can't be set synchronously. It was `animationFrame` before, but it works unstable with MS browsers.

`Polymer.Async.idlePeriod` in simple words means: "Hey, dialog is completely shown (at the end of possible showing animations in future) and focus is set" 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/16#-:-Krj1vvnF3uhwB1zNcxj:b-c9fkt6)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-overlay/16#-:-KrjKsZT98SkCGazSA2X:bnfp4nl)*

**Pull request merged**
