### PR TITLE
Do not focus overlay if focus is already in content

### LINKED ISSUE #73: Don't focus the overlay on open if it already has focus
This concerns `focus-trap`ped overlays like `vaadin-dialog`.

Related issue: https://github.com/vaadin/vaadin-dialog-flow/issues/55

### PR DESCRIPTION
**Pull request by manolo**
Fixes #73

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/74)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[theme/lumo/vaadin-overlay.html, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9iQ6k1EJvBcN2JRWKb:-L9iQ6k1EJvBcN2JRWKc:b-b3310d) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/35967edbf597e6a146ce7d2461e5e6f7517cd766/theme/lumo/vaadin-overlay.html#L5)):*
> ```HTML
> <dom-module id="demo-vaadin-overlay" theme-for="vaadin-overlay">
>   <template>
>     <style include="lumo-overlay">
> ```

need to add the following comment to make stylelint not complain:
```
/* stylelint-disable no-empty-source */
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/lumo/vaadin-overlay.html, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9iQ6k1EJvBcN2JRWKb:-L9iUyKPB9tiHF2zBPYn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/35967edbf597e6a146ce7d2461e5e6f7517cd766/theme/lumo/vaadin-overlay.html#L5)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

need to add the following comment to make stylelint not complain:
```
/* stylelint-disable no-empty-source */
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by tomivirkki** [comment]
*[theme/lumo/vaadin-overlay.html, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9iQ6k1EJvBcN2JRWKb:-L9jmK_06Bh17Y3i3vnk:b-wl5us5) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/35967edbf597e6a146ce7d2461e5e6f7517cd766/theme/lumo/vaadin-overlay.html#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why was this module added here in the Lumo styles? It will get included everywhere, not just the demos (that the id "demo-vaadin-overlay" suggests). Preferably move this module to the demos.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 373 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9jn6Ch8BCQMiUI_zOS:-L9jn6Ch8BCQMiUI_zOT:bh5o35f) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/src/vaadin-overlay.html#L373)):*
> ```HTML
> 
>           Polymer.RenderStatus.afterNextRender(this, () => {
>             if (this.focusTrap && !(this._focusedElement = this.shadowRoot.activeElement)) {
> ```

Do not add new unused variables in the element source code just for the demos.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by tomivirkki** [comment]
*[src/vaadin-overlay.html, line 373 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9jn6Ch8BCQMiUI_zOS:-L9jnVaCA78Syy5z-LGs:b-wdp6dn) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/src/vaadin-overlay.html#L373)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Do not add new unused variables in the element source code just for the demos.
</blockquote></details>

...mean to say "just for the tests."

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-overlay.html, line 373 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9jn6Ch8BCQMiUI_zOS:-L9k1EthAGZ7qhWZjya1:b-ot5fug) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/src/vaadin-overlay.html#L373)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

...mean to say "just for the tests."
</blockquote></details>

`_focusedElement` is needed in the code bellow. It stores the actual element focused so as `_cycleTab` can do its work, thus we need to set this variable here.

---

*[theme/lumo/vaadin-overlay.html, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9iQ6k1EJvBcN2JRWKb:-L9k1fL_7HYdOr8wYhBf:br4gwop) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/35967edbf597e6a146ce7d2461e5e6f7517cd766/theme/lumo/vaadin-overlay.html#L5)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why was this module added here in the Lumo styles? It will get included everywhere, not just the demos (that the id "demo-vaadin-overlay" suggests). Preferably move this module to the demos.
</blockquote></details>

It was first included there in my branch, but @jouni suggested in slack that it could be here, so I moved it.
If you rather to move back to demo, I'll do, otherwise I'll update the id here. 
I think having this here is better, it's confusing that the theme styles the overlay but it's not applied.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by platosha** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-overlay.html, line 373 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9jn6Ch8BCQMiUI_zOS:-L9kLrKE18Mpi3Z6tJ90:b-hlgcsa) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/src/vaadin-overlay.html#L373)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

`_focusedElement` is needed in the code bellow. It stores the actual element focused so as `_cycleTab` can do its work, thus we need to set this variable here.
</blockquote></details>

Should work without `_focusedElement` assignment here. `_cycleTab` will reduce through focusables and find it.

This assignment syntax is weird. And, apart from that, it might confuse what `_cycleTab` does, because `this.shadowRoot.activeElement` does only pick direct shadow children, although `_cycleTab` finds deep shadow children too.

Consider focus on the `<input>` in this tree:

```html
<vaadin-overlay>
  ::shadow-root
    ...
    <my-overlay-content>
      ::shadow-root
      <vaadin-text-field>
         ::shadow-root
           ...
           <input>
      </vaadin-text-field>
      <vaadin-button></vaadin-button>
    </my-overlay-content>
</vaadin-overlay>
```

`this` is the overlay, so `this.shadowRoot.activeElement` will point to `<my-overlay-content>`. This is enough for the check on this commented line here, as it does not matter where the focus actually is in the overlay, we only need to detect that it’s somewhere in. But `_cycleTab` needs to go deeper in shadow roots to move the focus in the expected way.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/index.html, line 206 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9kQ2ph6bFWJKv9bsZG:-L9kQ2ph6bFWJKv9bsZH:bjusbn4) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/demo/index.html#L206)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Focus Trap</h3>
> ```

There is another demo for the focus trap already.

Let us keep one demo per feature.

---

*[test/vaadin-overlay.html, line 660 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9kSGRS6U_jR-afdrqn:-L9kSGRS6U_jR-afdrqo:b-a4ys4h) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/test/vaadin-overlay.html#L660)):*
> ```HTML
>           overlay.opened = true;
>         });
> ```

BTW Now that tab handling is programmatic, would be nice to test it too. I’m curious with how it works in `<container-with-shadow>` in particular. 

- open the overlay, focus the first input in `<container-with-shadow>`
- dispatch a <kbd>Tab</kbd>
- expected: next focusable in `<container-with-shadow>` is focused

Focus might jump out from `<container-with-shadow>` in case if `_cycleTab` is incorrect about deep shadow focusables.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[demo/index.html, line 206 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9kQ2ph6bFWJKv9bsZG:-L9koPnOA9XuD2Bvi00Z:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/demo/index.html#L206)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

There is another demo for the focus trap already.

Let us keep one demo per feature.
</blockquote></details>

Done.

---

*[src/vaadin-overlay.html, line 373 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9jn6Ch8BCQMiUI_zOS:-L9l3vsu9nGMt4ubgmOT:bxo2fua) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/src/vaadin-overlay.html#L373)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should work without `_focusedElement` assignment here. `_cycleTab` will reduce through focusables and find it.

This assignment syntax is weird. And, apart from that, it might confuse what `_cycleTab` does, because `this.shadowRoot.activeElement` does only pick direct shadow children, although `_cycleTab` finds deep shadow children too.

Consider focus on the `<input>` in this tree:

```html
<vaadin-overlay>
  ::shadow-root
    ...
    <my-overlay-content>
      ::shadow-root
      <vaadin-text-field>
         ::shadow-root
           ...
           <input>
      </vaadin-text-field>
      <vaadin-button></vaadin-button>
    </my-overlay-content>
</vaadin-overlay>
```

`this` is the overlay, so `this.shadowRoot.activeElement` will point to `<my-overlay-content>`. This is enough for the check on this commented line here, as it does not matter where the focus actually is in the overlay, we only need to detect that it’s somewhere in. But `_cycleTab` needs to go deeper in shadow roots to move the focus in the expected way.
</blockquote></details>

@tomivirkki  @platosha  simplified `_cycleTab` so as ti does not need the `_focusedElement` private property.

---

*[test/vaadin-overlay.html, line 660 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9kSGRS6U_jR-afdrqn:-L9l5r8L2fhJWvs2a5aS:b-xah6tt) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/9b1a284e8e6834d6d7a64f41b0969b336a32f71c/test/vaadin-overlay.html#L660)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW Now that tab handling is programmatic, would be nice to test it too. I’m curious with how it works in `<container-with-shadow>` in particular. 

- open the overlay, focus the first input in `<container-with-shadow>`
- dispatch a <kbd>Tab</kbd>
- expected: next focusable in `<container-with-shadow>` is focused

Focus might jump out from `<container-with-shadow>` in case if `_cycleTab` is incorrect about deep shadow focusables.
</blockquote></details>

Running the test with the complete `tab` and `shift-tab` sequence for the shadow fixture

---

*[theme/lumo/vaadin-overlay.html, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9iQ6k1EJvBcN2JRWKb:-L9koB2J11ItfyH66a6O:b-fy1235) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/35967edbf597e6a146ce7d2461e5e6f7517cd766/theme/lumo/vaadin-overlay.html#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It was first included there in my branch, but @jouni suggested in slack that it could be here, so I moved it.
If you rather to move back to demo, I'll do, otherwise I'll update the id here. 
I think having this here is better, it's confusing that the theme styles the overlay but it's not applied.
</blockquote></details>

Removed demo prefix. We cannot name this lumo-overlay because the id is already used. Using lumo-vaadin-overlay instead

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by tomivirkki** [comment]
*[theme/lumo/vaadin-overlay.html, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9iQ6k1EJvBcN2JRWKb:-L9nMWn75Yc83TElxfUw:b9v13zo) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/35967edbf597e6a146ce7d2461e5e6f7517cd766/theme/lumo/vaadin-overlay.html#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Removed demo prefix. We cannot name this lumo-overlay because the id is already used. Using lumo-vaadin-overlay instead
</blockquote></details>

Yeah the naming is not misaligned (other elements don't use `)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by tomivirkki** [comment]
*[theme/lumo/vaadin-overlay.html, line 5 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9iQ6k1EJvBcN2JRWKb:-L9nN7Oi0daVaZIuBAt4:b-ib9oom) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/35967edbf597e6a146ce7d2461e5e6f7517cd766/theme/lumo/vaadin-overlay.html#L5)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Yeah the naming is not misaligned (other elements don't use `)
</blockquote></details>

Reviewable messed up the comment again. But anyway, LGTM. The naming being slightly misaligned isn't that big a problem

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by platosha** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 56 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nRAhP7bDUhnPgH13S:-L9nRAhP7bDUhnPgH13T:b-ljrvgw) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L56)):*
> ```HTML
>     <demo-snippet>
>       <template>
>         <vaadin-overlay with-backdrop focus-trap id="overlay2">
> ```

Apparently `id` is not used anymore, let’s remove.

---

*[demo/index.html, line 58 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nU-vo2iXjk_gkBTAk:-L9nU-vo2iXjk_gkBTAl:b7bkyvu) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L58)):*
> ```HTML
>         <vaadin-overlay with-backdrop focus-trap id="overlay2">
>           <template>
>             <vaadin-form-layout style="width: 400px">
> ```

Visual prettiness is not a good reason to bring `<vaadin-form-layout>` dependency. These demos are not public anyway.

You can use `"max-width"` inline style on the overlay or linebreaks & paragraphs in the content if the width gets annoying.

---

*[demo/index.html, line 62 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nUXjn7WXIQ3T9gS1B:-L9nUXjn7WXIQ3T9gS1C:bh3t62z) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L62)):*
> ```HTML
>               <button>native button</button>
>               <button tabindex="-1">button with tabindex="-1"</button>
>               <vaadin-text-field placeholder="vaadin-text-field programatically focused"></vaadin-text-field>
> ```

`<vaadin-text-field>` is included in the demos and tests, but not a bower dependency. This relies on transitive dependency from `<vaadin-date-picker>`. 

From the maintenance point of view, having less dependencies is easier, so would prefer to remove the imports if possible.

---

*[src/vaadin-overlay.html, line 510 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nQ1sk9oCjcAdiRLRB:-L9nQ1sk9oCjcAdiRLRC:bqnawid) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/src/vaadin-overlay.html#L510)):*
> ```HTML
> 
>         if (index === undefined) {
>           index = focusableElements.indexOf(this._focusedElement(focusableElements));
> ```

BTW nitpick: it seems redundant to iterate over `focusableElements` to find the one, then to iterate again in `indexOf` to find the index of the one. Consider returning the index right away.

---

*[test/vaadin-overlay.html, line 666 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nOSoB5F2QQgzPVtVG:-L9nOSoB5F2QQgzPVtVH:b3nh58b) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/test/vaadin-overlay.html#L666)):*
> ```HTML
>             for (let i = 0; i < focusableElements.length; i++) {
>               expect(overlay._focusedElement()).to.eql(focusableElements[i]);
>               MockInteractions.pressAndReleaseKeyOn(document.body, 9, [], 'Tab');
> ```

BTW nitpick again: native behavior is: moving focus on keydown, not keyup or keypress. No need to dispatch key release. Without it, the test would be more strict, which is a plus.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/index.html, line 58 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nU-vo2iXjk_gkBTAk:-L9n_s3oC1syaQee2tzk:b-dn8jl2) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L58)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Visual prettiness is not a good reason to bring `<vaadin-form-layout>` dependency. These demos are not public anyway.

You can use `"max-width"` inline style on the overlay or linebreaks & paragraphs in the content if the width gets annoying.
</blockquote></details>

Usage of form-layout here is for checking that fields nested in shadow work

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/index.html, line 58 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nU-vo2iXjk_gkBTAk:-L9nkwX87o0cz9XutgD8:b-goffk9) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L58)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Usage of form-layout here is for checking that fields nested in shadow work
</blockquote></details>

Irrelevant, the fields are not in the form layout’s shadow but in the light DOM.

Form layout does not have tabindex and does not have anything focusable in the shadow.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by manolo** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/index.html, line 56 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nRAhP7bDUhnPgH13S:-L9nq55FB4g-k3BqlWHi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L56)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Apparently `id` is not used anymore, let’s remove.
</blockquote></details>

Done.

---

*[demo/index.html, line 58 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nU-vo2iXjk_gkBTAk:-L9nreJz62pkweZoLijp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L58)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Irrelevant, the fields are not in the form layout’s shadow but in the light DOM.

Form layout does not have tabindex and does not have anything focusable in the shadow.
</blockquote></details>

Done.

---

*[demo/index.html, line 62 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nUXjn7WXIQ3T9gS1B:-L9nsGoj2JHRfl_QLzXE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L62)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`<vaadin-text-field>` is included in the demos and tests, but not a bower dependency. This relies on transitive dependency from `<vaadin-date-picker>`. 

From the maintenance point of view, having less dependencies is easier, so would prefer to remove the imports if possible.
</blockquote></details>

Done.

---

*[src/vaadin-overlay.html, line 510 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nQ1sk9oCjcAdiRLRB:-L9o-Yo1C9IPWf5PpUKb:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/src/vaadin-overlay.html#L510)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW nitpick: it seems redundant to iterate over `focusableElements` to find the one, then to iterate again in `indexOf` to find the index of the one. Consider returning the index right away.
</blockquote></details>

Done.

---

*[test/vaadin-overlay.html, line 666 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nOSoB5F2QQgzPVtVG:-L9o-Zgz24GQqXCEaWlF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/test/vaadin-overlay.html#L666)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW nitpick again: native behavior is: moving focus on keydown, not keyup or keypress. No need to dispatch key release. Without it, the test would be more strict, which is a plus.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-overlay.html, line 502 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9o3l7n0q9PY9lz-ez-:-L9o3l7n0q9PY9lz-ez0:b-wdin8y) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/1c88fc2cac5a85af2a3c8f12240925b6e8f82ffc/src/vaadin-overlay.html#L502)):*
> ```HTML
>       _focusedIndex(elements) {
>         elements = elements || this._getFocusableElements();
>         return elements.reduce((prev, e) => {
> ```

BTW nitpick: the index is provided in reduce callback arguments:

`elements.reduce((prev, e, index) => {`

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/index.html, line 56 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nRAhP7bDUhnPgH13S:-L9o4KTV1vt2Qa3oGMpj:bfhqml6) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L56)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by manolo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/index.html, line 56 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9nRAhP7bDUhnPgH13S:-L9oEk0qBCWPC1c4I_TM:b2nidxv) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/e4c95324c892f218467f3d3fe33613e0f89a0d29/demo/index.html#L56)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

ups

---

*[src/vaadin-overlay.html, line 502 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-L9o3l7n0q9PY9lz-ez-:-L9oEiBS-63x_KQoSnrQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/1c88fc2cac5a85af2a3c8f12240925b6e8f82ffc/src/vaadin-overlay.html#L502)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW nitpick: the index is provided in reduce callback arguments:

`elements.reduce((prev, e, index) => {`

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-:-L9oMgrqEedzzdA-FESi:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-overlay/74#-:-L9obzpl2HD8Gq0l8jA7:bnfp4nl)*

**Pull request merged**
