### PR TITLE
Manual rendering of the content

### PR DESCRIPTION
**Pull request by yuriy-fix**
Connected to https://github.com/vaadin/components-team-tasks/issues/409

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)

### CODE REVIEW

**Review by tomivirkki — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @YuriyVaadin)

___
*[src/vaadin-overlay.html, line 789 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvmRAQ-jcsn3uFrmY9:-LKvmRAQ-jcsn3uFrmYA:b-g5z017) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/efe51bf0e04d0af1bdb61d8e4aae5028e193bbf9/src/vaadin-overlay.html#L789)):*
> ```HTML
>         }
> 
>         this.renderer.call(this.owner, this, this.owner, this.model);
> ```

Shouldn't the second parameter (root) be `this.content`?
___
*[src/vaadin-overlay.html, line 820 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvlrmw02Gf7L2N1xFg:-LKvlrmw02Gf7L2N1xFh:b-p3gq6x) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/efe51bf0e04d0af1bdb61d8e4aae5028e193bbf9/src/vaadin-overlay.html#L820)):*
> ```HTML
>           }
> 
>           this.renderer.call(owner, this.content, owner, model);
> ```

This should call `this.render()`

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @YuriyVaadin)

___
*[src/vaadin-overlay.html, line 789 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvmRAQ-jcsn3uFrmY9:-LKvnVVNAT512rwWpC1m:b-x610hs) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/efe51bf0e04d0af1bdb61d8e4aae5028e193bbf9/src/vaadin-overlay.html#L789)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Shouldn't the second parameter (root) be `this.content`?
</blockquote></details>

`this.content` is set in `_templateOrRendererChanged` and always equals `this`, so I've decided to simplify it, but changed now.
___
*[src/vaadin-overlay.html, line 820 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvlrmw02Gf7L2N1xFg:-LKvnkxHBsqs_1tr7ZnI:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/efe51bf0e04d0af1bdb61d8e4aae5028e193bbf9/src/vaadin-overlay.html#L820)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This should call `this.render()`
</blockquote></details>

Updated.

**Review by manolo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @manolo, @tomivirkki, and @YuriyVaadin)

___
*[demo/index.html, line 66 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvoxVHBe0cH39bLb2F:-LKvoxVHBe0cH39bLb2G:bbjfti2) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/demo/index.html#L66)):*
> ```HTML
>         <script>
>           var dynamicOverlay = document.querySelector('#manual-renderer');
>           var dynamicOverlayBtn = document.querySelector('#btn-manual-renderer');
> ```

Why `var` and why log variable names?
___
*[src/vaadin-overlay.html, line 785 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvoBUW88Y14kJgKYiP:-LKvoBUW88Y14kJgKYiQ:bbr69ww) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/efe51bf0e04d0af1bdb61d8e4aae5028e193bbf9/src/vaadin-overlay.html#L785)):*
> ```HTML
>        */
>       render() {
>         if (!this.renderer) {
> ```

For these simple cases I prefer one block logic, it's easier to read. Not a blocker though

```
if (this.renderer) {
   this.renderer.cal ....
}
```

**Review by manolo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @manolo, @tomivirkki, and @YuriyVaadin)

___
*[demo/index.html, line 66 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvoxVHBe0cH39bLb2F:-LKvpAEzBSHRftaEetLu:b-sd38fx) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/demo/index.html#L66)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why `var` and why log variable names?
</blockquote></details>

long vars I meant

**Review by manolo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @manolo, @tomivirkki, and @YuriyVaadin)

___
*[test/renderer.html, line 128 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvpSGFBZBe5Do3iTHX:-LKvpSGFBZBe5Do3iTHY:b-plh11b) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/test/renderer.html#L128)):*
> ```HTML
>           overlay.renderer = () => spy();
>           overlay.render();
>           expect(spy.calledTwice).to.be.true;
> ```

why is called twice?

**Comment by tomivirkki** [comment]
___
*[test/renderer.html, line 126 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKw-8nA-CyuoTfdxa-e:-LKw-8nB82kzbFJiHkPl:bifj447) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/test/renderer.html#L126)):*
> ```HTML
>         it('should be possible to manually invoke renderer', () => {
>           const spy = sinon.spy();
>           overlay.renderer = () => spy();
> ```

The spy can be assigned as the renderer directly. For example:
`overlay.renderer = sinon.spy()`
...
`expect(overlay.renderer.called...).to.be.true`
which makes is more readable and shorter

**Comment by tomivirkki** [comment]
___
*[demo/index.html, line 57 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKw0mAp8QckhU67uPFm:-LKw0mAp8QckhU67uPFn:bcpshig) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/demo/index.html#L57)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Dynamically updated content of the overlay</h3>
> ```

Wrong case

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @manolo, @tomivirkki, and @YuriyVaadin)

___
*[demo/index.html, line 57 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKw0mAp8QckhU67uPFm:-LKzJGzJ3segwYW_02Oz:b-bu91xm) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/demo/index.html#L57)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Wrong case
</blockquote></details>

Updated
___
*[demo/index.html, line 66 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvoxVHBe0cH39bLb2F:-LKzJThJD2P43bAUX5-3:b-excu4s) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/demo/index.html#L66)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

long vars I meant
</blockquote></details>

It's done on purpose not to match other overlays and buttons in the scope. (We are not using demo-snippet over here)
___
*[src/vaadin-overlay.html, line 785 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvoBUW88Y14kJgKYiP:-LKzJhbd0LtpEC1K9ajx:b-bw8e14) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/efe51bf0e04d0af1bdb61d8e4aae5028e193bbf9/src/vaadin-overlay.html#L785)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

For these simple cases I prefer one block logic, it's easier to read. Not a blocker though

```
if (this.renderer) {
   this.renderer.cal ....
}
```
</blockquote></details>

Updated.
___
*[test/renderer.html, line 126 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKw-8nA-CyuoTfdxa-e:-LKzJisU00sa164Uch6o:b-munwrr) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/test/renderer.html#L126)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The spy can be assigned as the renderer directly. For example:
`overlay.renderer = sinon.spy()`
...
`expect(overlay.renderer.called...).to.be.true`
which makes is more readable and shorter
</blockquote></details>

Thanks, updated
___
*[test/renderer.html, line 128 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvpSGFBZBe5Do3iTHX:-LKzJlPMAi6xNkX9l1U_:b9e1f0g) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/test/renderer.html#L128)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why is called twice?
</blockquote></details>

Firstly on `renderer` assignment and secondly on `render` call

**Review by manolo — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-:-LKzOs6E55FJNnvH1I53:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @tomivirkki)

___
*[demo/index.html, line 66 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvoxVHBe0cH39bLb2F:-LKzOYpb8AM3Ow8L_VpS:b-mnm5wb) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/demo/index.html#L66)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

It's done on purpose not to match other overlays and buttons in the scope. (We are not using demo-snippet over here)
</blockquote></details>

clear, thanks
___
*[test/renderer.html, line 128 at r2](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKvpSGFBZBe5Do3iTHX:-LKzOley4ksD9QwDR6cr:b32wtd) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/57e859ff6799c689dc3eab9575602805c4199196/test/renderer.html#L128)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Firstly on `renderer` assignment and secondly on `render` call
</blockquote></details>

ok

**Review by tomivirkki — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-:-LKzZd2c4D_vzcQsVwxN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by tomivirkki** [comment]
___
*[src/vaadin-overlay.html, line 785 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKzoHBCBpQgXFRjirHq:-LKzoHBCBpQgXFRjirHr:bgilrnq) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/c2d38e0d2fc7541a97a1253d0493638a38aa32ee/src/vaadin-overlay.html#L785)):*
> ```HTML
>        */
>       render() {
>         if (this.renderer) {
> ```

Oh, one more question. shouldn't this check `this.content` and `this.owner` also as they should always be available? Or are they guaranteed to exist when this is called (even externally)?

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

___
*[src/vaadin-overlay.html, line 785 at r3](https://reviewable.io/reviews/vaadin/vaadin-overlay/119#-LKzoHBCBpQgXFRjirHq:-LL-0o7aD4L2NA1hVjXI:b-ktrb49) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/c2d38e0d2fc7541a97a1253d0493638a38aa32ee/src/vaadin-overlay.html#L785)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Oh, one more question. shouldn't this check `this.content` and `this.owner` also as they should always be available? Or are they guaranteed to exist when this is called (even externally)?
</blockquote></details>

The `content`, its existence is guaranteed. As for the `owner` it's guaranteed to be set from external and shouldn't be checked over here.

**Review by tomivirkki — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/119)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
