### PR TITLE
Throw error when template and renderer are used simultaneously

### PR DESCRIPTION
**Pull request by yuriy-fix**
Connected to https://github.com/vaadin/components-team-tasks/issues/391

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104)

### CODE REVIEW

**Review by platosha — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104)* status: all files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin)

___
*[src/vaadin-overlay.html, line 743 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/104#-LIGLnpY-_Y14wKT3IcS:-LIGLnpY-_Y14wKT3IcT:b-87pi01) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/861bdb404bdc0908c49f0139705748f49a7f32b8/src/vaadin-overlay.html#L743)):*
> ```HTML
>           this.content = this;
> 
>           while (this.content.firstChild) {
> ```

Should only clean up the old DOM content when a new `renderer` is assigned.

It seems that this would clean up the old content on a model change too.

Please add a test for that.

**Review by yuriy-fix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @platosha and @YuriyVaadin)

___
*[src/vaadin-overlay.html, line 743 at r1](https://reviewable.io/reviews/vaadin/vaadin-overlay/104#-LIGLnpY-_Y14wKT3IcS:-LIGQPWz6h15sLM5u0wo:b-5ue710) ([raw file](https://github.com/vaadin/vaadin-overlay/blob/861bdb404bdc0908c49f0139705748f49a7f32b8/src/vaadin-overlay.html#L743)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should only clean up the old DOM content when a new `renderer` is assigned.

It seems that this would clean up the old content on a model change too.

Please add a test for that.
</blockquote></details>

Updated and tests are added.

**Review by platosha — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by platosha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104#-:-LIGU5JcEtSMWWgp2WIg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by platosha — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by platosha — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by platosha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104#-:-LILU7f80mG9Ky2KypQR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by manolo — APPROVED** [review]
:lgtm: but CI timed out,  restarted, let's see if it passes

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104#-:-LIQa92h5vK_5JZEJh4z:bg9sps6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by web-padawan — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by web-padawan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-overlay/104)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
